const dictionary = [
  
  {
    id: 1,
    word: "buug",
    language: "somali",
    type: "noun",
    traditionalMeaning: "book",
    modernMeaning: null,
    example: "Buugga waa mid fiican.",
    synonyms: ["qoraal", "buugaag"],
    isTech: false,
    explanationEn: "A written or printed work consisting of pages bound together, used for reading, study, or reference.",
    explanationSo: "Waa shay qoraal ah oo xidhan oo lagu aqriyo ama laga barto macluumaad."
  },
  {
    id: 2,
    word: "guri",
    language: "somali",
    type: "noun",
    traditionalMeaning: "house / home",
    modernMeaning: null,
    example: "Gurigaygu waa weyn yahay.",
    synonyms: ["hoy", "meel deganaansho"],
    isTech: false,
    explanationEn: "A building where a person or family lives; a place of shelter and belonging.",
    explanationSo: "Waa dhisme ay degaan qoys ama qof; meel ay dadku ku nool yihiin oo ay ku nabad galaan."
  },
  {
    id: 3,
    word: "biyo",
    language: "somali",
    type: "noun",
    traditionalMeaning: "water",
    modernMeaning: null,
    example: "Biyaha badda waa cusbo.",
    synonyms: ["roob (rain water)"],
    isTech: false,
    explanationEn: "A clear, colourless liquid essential for all life; water in its natural form.",
    explanationSo: "Waa dareeraha daahir ah ee aan midab lahayn oo nolosha ku xidna; biyaha dabiiciga ah."
  },
  {
    id: 4,
    word: "nabad",
    language: "somali",
    type: "noun",
    traditionalMeaning: "peace / greeting",
    modernMeaning: null,
    example: "Nabad iyo nolol.",
    synonyms: ["xasilloon", "aamaanshaha"],
    isTech: false,
    explanationEn: "A state of harmony and absence of conflict; also used as a common Somali greeting meaning 'peace'.",
    explanationSo: "Xaalad naxariis iyo is-afgarad ah; sidoo kale waa salaan caadi ah oo Soomaali ah oo micnaheedu yahay 'nabadgelyo'."
  },
  {
    id: 5,
    word: "waxbarasho",
    language: "somali",
    type: "noun",
    traditionalMeaning: "education / learning",
    modernMeaning: null,
    example: "Waxbarashaddu waa muhiim.",
    synonyms: ["tacliim", "barashada"],
    isTech: false,
    explanationEn: "The process of acquiring knowledge, skills, and values through study or teaching.",
    explanationSo: "Habka lagu helayo aqoon, xirfad, iyo qiimayaal iyada oo loo marayo barasho ama waxbarasho."
  },
  {
    id: 6,
    word: "dhul",
    language: "somali",
    type: "noun",
    traditionalMeaning: "land / earth / ground",
    modernMeaning: null,
    example: "Dhulku waa mid qurxoon.",
    synonyms: ["carrada", "aduunka"],
    isTech: false,
    explanationEn: "The solid surface of the earth; ground, soil, or a territory belonging to a group or nation.",
    explanationSo: "Dhulka adduunka ee adag; carrada, ciidda, ama gobol u gaar ah qolo ama wadan."
  },
  {
    id: 7,
    word: "xidid",
    language: "somali",
    type: "noun",
    traditionalMeaning: "root / origin",
    modernMeaning: null,
    example: "Xididkaygu waa Soomaaliya.",
    synonyms: ["asalka", "abtirsiinyo"],
    isTech: false,
    explanationEn: "The part of a plant that anchors it in the ground; also used figuratively for one's ancestry or origin.",
    explanationSo: "Qaybta geedka ee ciidda ku xidnaanta; sidoo kale si la filayso waxaa loo isticmaalaa xididka qof."
  },
  {
    id: 8,
    word: "feker",
    language: "somali",
    type: "noun",
    traditionalMeaning: "thought / idea",
    modernMeaning: null,
    example: "Fekerkaaga waa fiican yahay.",
    synonyms: ["fikrad", "aragti"],
    isTech: false,
    explanationEn: "A mental process of considering or reasoning; an idea or opinion formed in the mind.",
    explanationSo: "Hawl maskax ah oo ah in la is-arko ama la fikiyo; fikrad ama ra'yi maskaxda ka dhashay."
  },

  
  {
    id: 9,
    word: "knowledge",
    language: "english",
    type: "noun",
    traditionalMeaning: "aqoon",
    modernMeaning: null,
    example: "Knowledge is power — Aqoontu waa awoodda.",
    synonyms: ["information", "wisdom", "understanding"],
    isTech: false,
    explanationEn: "Facts, information, and skills acquired through experience or education.",
    explanationSo: "Xaqiiqooyin, macluumaad, iyo xirfadood la helay iyada oo loo marayo khibrad ama waxbarasho."
  },
  {
    id: 10,
    word: "language",
    language: "english",
    type: "noun",
    traditionalMeaning: "luqad",
    modernMeaning: null,
    example: "Somali is a beautiful language.",
    synonyms: ["tongue", "dialect", "speech"],
    isTech: false,
    explanationEn: "A system of communication using words, grammar, and sounds used by a people.",
    explanationSo: "Nidaam xiriir ah oo isticmaala ereyada, naxwaha, iyo codadka ee dadku isticmaalaan."
  },
  {
    id: 11,
    word: "science",
    language: "english",
    type: "noun",
    traditionalMeaning: "sayniska",
    modernMeaning: null,
    example: "Science helps us understand the world.",
    synonyms: ["research", "study"],
    isTech: false,
    explanationEn: "The systematic study of the physical and natural world through observation and experiment.",
    explanationSo: "Daraasadda nidaamsan ee adduunka jirka iyo dabiiciga ah iyada oo loo marayo arista iyo tijaabada."
  },
  {
    id: 12,
    word: "culture",
    language: "english",
    type: "noun",
    traditionalMeaning: "dhaqan",
    modernMeaning: null,
    example: "Somali culture is rich and diverse.",
    synonyms: ["tradition", "heritage", "civilization"],
    isTech: false,
    explanationEn: "The ideas, customs, and social behaviour of a particular people or society.",
    explanationSo: "Fikradaha, caadooyinka, iyo dhaqanka bulshada ee shacab ama bulsho gaar ah."
  },

  
  {
    id: 13,
    word: "artificial intelligence",
    language: "english",
    type: "noun",
    traditionalMeaning: "Caqliga Macmalka ah",
    modernMeaning: "Caqli",
    example: "Artificial intelligence is changing the world.",
    synonyms: ["AI", "machine learning", "deep learning"],
    isTech: true,
    explanationEn: "The simulation of human intelligence processes by computer systems, including learning and problem-solving.",
    explanationSo: "Mashaqada caqliga aadanaha ee nidaamyada kombiyuutarka, oo ay ku jiraan barashada iyo xallinta dhibaatooyinka."
  },
  {
    id: 14,
    word: "algorithm",
    language: "english",
    type: "noun",
    traditionalMeaning: "Qaacidada Xisaabinta",
    modernMeaning: "Qaacido",
    example: "Search engines use algorithms to rank results.",
    synonyms: ["procedure", "process", "formula"],
    isTech: true,
    explanationEn: "A set of rules or instructions followed by a computer to solve a problem or complete a task.",
    explanationSo: "Jilbaha ama tilmaamaha kombiyuutarka raacaa si uu dhibaato u xalliyo ama hawl u dhammaystiro."
  },
  {
    id: 15,
    word: "programming",
    language: "english",
    type: "noun",
    traditionalMeaning: "Barnaamijyeynta Kombiyuutarka",
    modernMeaning: "Barnaamijsi",
    example: "Programming is the language of the future.",
    synonyms: ["coding", "software development"],
    isTech: true,
    explanationEn: "The process of writing instructions for a computer to perform specific tasks.",
    explanationSo: "Habka lagu qoro tilmaamaha kombiyuutarka si uu hawlo gaar ah u qabto."
  },
  {
    id: 16,
    word: "database",
    language: "english",
    type: "noun",
    traditionalMeaning: "Kaydka Xogta",
    modernMeaning: "Kayd-xog",
    example: "The database stores millions of records.",
    synonyms: ["data store", "repository"],
    isTech: true,
    explanationEn: "An organised collection of data stored and accessed electronically.",
    explanationSo: "Ururinta xogta nidaamsan ee elektaroonig lagu kaydiyay lana geli karo."
  },
  {
    id: 17,
    word: "internet",
    language: "english",
    type: "noun",
    traditionalMeaning: "Shabakadda Adduunka",
    modernMeaning: "Xarig",
    example: "The internet connects the world.",
    synonyms: ["web", "network", "online"],
    isTech: true,
    explanationEn: "A global network of computers and servers connected by communication protocols.",
    explanationSo: "Shabakadda adduunka ee kombiyuutarrada iyo server-yada xidha xiriiro xiriir."
  },
  {
    id: 18,
    word: "cybersecurity",
    language: "english",
    type: "noun",
    traditionalMeaning: "Amniga Teknoolojiyada",
    modernMeaning: "Amni-xarig",
    example: "Cybersecurity protects your digital life.",
    synonyms: ["digital security", "information security"],
    isTech: true,
    explanationEn: "The practice of protecting computers, networks, and data from digital attacks.",
    explanationSo: "Dhaqanka ilaalinta kombiyuutarrada, shabakadaha, iyo xogta weeraryada dijitaalka."
  },
  {
    id: 19,
    word: "cloud computing",
    language: "english",
    type: "noun",
    traditionalMeaning: "keydinta xogta ee nidaam danabeysan",
    modernMeaning: "keyd-daruurid",
    example: "Cloud computing enables remote work.",
    synonyms: ["cloud storage", "SaaS", "remote computing"],
    isTech: true,
    explanationEn: "The delivery of computing services over the internet, including storage and processing.",
    explanationSo: "Bixinta adeegyada kombiyuutarka iyada oo loo marayo internet, oo ay ku jiraan kaydinta iyo hawlgelinta."
  },
  {
    id: 20,
    word: "blockchain",
    language: "english",
    type: "noun",
    traditionalMeaning: "habka xidhxidhka xogta ee ammaan ah",
    modernMeaning: "xidhidhka habsami socodka xogta lacagaha dijitaalka ah",
    example: "Blockchain powers cryptocurrencies.",
    synonyms: ["distributed ledger", "crypto"],
    isTech: true,
    explanationEn: "A distributed digital ledger that records transactions across multiple computers securely.",
    explanationSo: "Diiwaanka dijitaalka ah ee qaybsan ee diiwaangeliya macaamiladaha kombiyuutarrada badan si ammaan ah."
  },
  {
    id: 21,
    word: "software",
    language: "english",
    type: "noun",
    traditionalMeaning: "Barnaamijka Kombiyuutarka",
    modernMeaning: "Nidaam-kombiyuutar",
    example: "This software is open source.",
    synonyms: ["program", "application", "app"],
    isTech: true,
    explanationEn: "Programs and operating information used by a computer.",
    explanationSo: "Barnaamijyada iyo macluumaadka hawlgelinta ee kombiyuutarka isticmaalo."
  },

  {
    id: 22,
    word: "robot",
    language: "english",
    type: "noun",
    traditionalMeaning: "Mishiinka Aadanaha La Mid ah",
    modernMeaning: "Mishiin-aadane",
    example: "Robots are used in manufacturing.",
    synonyms: ["automaton", "android", "machine"],
    isTech: true,
    explanationEn: "A machine capable of carrying out complex actions automatically, often programmed by a computer.",
    explanationSo: "Mishiin awood u leh in uu si toos ah u qaabto hawlo adag, oo inta badan kombiyuutar barnaamij sameeyay."
  },
  {
    id: 23,
    word: "Sakariye",
    language: "Somali",
    type: "Person/ Shakhsi",
    traditionalMeaning: "Khabiir Kombiyuutar Sare ahna aaqoonyahan iyo aasaasaha shirkadda MakersLab",
    modernMeaning: "Zakarie idiris",
    example: "Sakariye waa aasaasaha shirkadda MakersLab.",
  },
  {
  id: 24,
  word: "startup",
  language: "english",
  type: "noun",
  traditionalMeaning: "Shirkad Cusub",
  modernMeaning: "Bilow-ganacsi",
  example: "He launched a tech startup in 2026.",
  synonyms: ["new company", "venture"],
  isTech: true,
  explanationEn: "A newly established business, especially one in the technology sector.",
  explanationSo: "Ganacsiga la aasaasay, gaar ahaan mid ku jira qaybta teknoolojiyada."
},
{
  id: 25,
  word: "innovation",
  language: "english",
  type: "noun",
  traditionalMeaning: "Hal-abuur",
  modernMeaning: "Abuur-cusub",
  example: "Innovation drives progress.",
  synonyms: ["creativity", "invention"],
  isTech: true,
  explanationEn: "The introduction of new ideas, methods, or products to improve processes or solve problems.",
  explanationSo: "Hordhaca fikradaha cusub, hababka, ama waxsoosaarka si loo wanaajin nidaamyada ama loo xalliyo dhibaatooyinka."
},
{
  id: 26,
  word: "data",
  language: "english",
  type: "noun",
  traditionalMeaning: "Xog",
  modernMeaning: "Xog",
  example: "Data is the new oil.",
  synonyms: ["information", "records"],
  isTech: true,
  explanationEn: "Facts and statistics collected for analysis or reference.",
  explanationSo: "Xaqiiqooyin iyo tirakoob la ururiyay si loo falanqeeyo ama loo tixraaco."
},
{
  id: 27,
  word: "server",
  language: "english",
  type: "noun",
  traditionalMeaning: "Adeege Kombiyuutar",
  modernMeaning: "Adeeg-xog",
  example: "The server is down.",
  synonyms: ["host", "backend machine"],
  isTech: true,
  explanationEn: "A computer or system that provides data and services to other computers over a network.",
  explanationSo: "Kombiyuutar ama nidaam bixiya xogta iyo adeegyada kombiyuutarrada kale iyada oo loo marayo shabakad."
},
{
  id: 28,
  word: "frontend",
  language: "english",
  type: "noun",
  traditionalMeaning: "Qaybta Hore ee Nidaamka",
  modernMeaning: "Hore-nidaam",
  example: "He works as a frontend developer.",
  synonyms: ["UI side", "client side"],
  isTech: true,
  explanationEn: "The part of a website or app that users interact with directly, visible in the browser.",
  explanationSo: "Qaybta websaydhka ama app-ka ee isticmaaluhu si toos ah uga dhexgalaan, muuqata browser-ka."
},
{
  id: 29,
  word: "backend",
  language: "english",
  type: "noun",
  traditionalMeaning: "Qaybta Dambe ee Nidaamka",
  modernMeaning: "Dambe-nidaam",
  example: "Backend handles database logic.",
  synonyms: ["server side"],
  isTech: true,
  explanationEn: "The server-side part of a website that users do not see, handling data and logic.",
  explanationSo: "Qaybta server-gaas ee websaydhka ee isticmaaluhu arkaynin, xogta iyo curiyeysa qaabila."
},
{
  id: 30,
  word: "API",
  language: "english",
  type: "noun",
  traditionalMeaning: "Isku-xirka Barnaamijyada",
  modernMeaning: "Xiriir-nidaam",
  example: "The app connects using an API.",
  synonyms: ["interface", "endpoint"],
  isTech: true,
  explanationEn: "A set of rules that allows different software applications to communicate with each other.",
  explanationSo: "Jilbaha u oggolaanaya barnaamijyada software-ka kala duwan in ay isku xiraan."
},
{
  id: 31,
  word: "encryption",
  language: "english",
  type: "noun",
  traditionalMeaning: "Siraynta Xogta",
  modernMeaning: "Sir-xog",
  example: "Encryption protects user data.",
  synonyms: ["data protection"],
  isTech: true,
  explanationEn: "The process of converting data into a code to prevent unauthorised access.",
  explanationSo: "Habka loo rogayo xogta kood si looga hortago gelitaanka aan la oggolayn."
},
{
  id: 32,
  word: "authentication",
  language: "english",
  type: "noun",
  traditionalMeaning: "Hubinta Aqoonsiga",
  modernMeaning: "Hubin-aqoonsi",
  example: "Two-factor authentication is secure.",
  synonyms: ["verification"],
  isTech: true,
  explanationEn: "The process of verifying the identity of a user or system before granting access.",
  explanationSo: "Habka loo xaqiijiyo aqoonsiga isticmaale ama nidaam kahor inta aan gelitaan la siin."
},
{
  id: 33,
  word: "biometric",
  language: "english",
  type: "noun",
  traditionalMeaning: "Aqoonsiga Jirka",
  modernMeaning: "Jir-aqoonsi",
  example: "Biometric login uses fingerprint.",
  synonyms: ["fingerprint ID"],
  isTech: true,
  explanationEn: "Technology using unique physical characteristics, such as fingerprints, to identify individuals.",
  explanationSo: "Teknoolojiyada isticmaalaysa sifooyinka jireed ee goonida ah, sida faraha, si loo aqoonsado shakhsiyaadka."
},
{
  id: 34,
  word: "machine learning",
  language: "english",
  type: "noun",
  traditionalMeaning: "Barashada Mashiinka",
  modernMeaning: "Baro-mashiin",
  example: "Machine learning improves predictions.",
  synonyms: ["ML"],
  isTech: true,
  explanationEn: "A type of AI where systems learn from data and improve their performance over time.",
  explanationSo: "Nooc AI ah oo nidaamyadu xogta ka baranayaan oo waqti ka waqti waxqabadkooda wanaajiyaan."
},
{
  id: 35,
  word: "user interface",
  language: "english",
  type: "noun",
  traditionalMeaning: "Isdhexgalka Isticmaalaha",
  modernMeaning: "Arag-dhexgal",
  example: "The user interface is clean.",
  synonyms: ["UI"],
  isTech: true,
  explanationEn: "The visual layout and controls through which a user interacts with a software application.",
  explanationSo: "Qaab-muuqaalka iyo kontarooliga uu isticmaaluhu uga dhexgalo barnaamijka software-ka."
},
{
  id: 36,
  word: "user experience",
  language: "english",
  type: "noun",
  traditionalMeaning: "Khibradda Isticmaalaha",
  modernMeaning: "Khibrad-isticmaal",
  example: "Good UX increases engagement.",
  synonyms: ["UX"],
  isTech: true,
  explanationEn: "The overall experience a person has when using a product, especially a digital one.",
  explanationSo: "Khibradda guud ee qofku helo isagoo isticmaalaya alaabta, gaar ahaan tan dijitaalka ah."
},
{
  id: 37,
  word: "bug",
  language: "english",
  type: "noun",
  traditionalMeaning: "Khalad Barnaamij",
  modernMeaning: "Cilad-kood",
  example: "There is a bug in the system.",
  synonyms: ["error"],
  isTech: true,
  explanationEn: "An error or flaw in a computer program that causes it to behave unexpectedly.",
  explanationSo: "Khalad ama cilad ku jirta barnaamijka kombiyuutarka oo keenta in uu si aan la filanayn u dhaqmo."
},
{
  id: 38,
  word: "debugging",
  language: "english",
  type: "noun",
  traditionalMeaning: "Sixidda Khaladaadka",
  modernMeaning: "Cilad-saar",
  example: "Debugging takes time.",
  synonyms: ["fixing errors"],
  isTech: true,
  explanationEn: "The process of finding and fixing errors in computer code.",
  explanationSo: "Habka la helaa oo la saxaya khaladaadka koodka kombiyuutarka."
},
{
  id: 39,
  word: "framework",
  language: "english",
  type: "noun",
  traditionalMeaning: "Qaab-dhismeed Barnaamij",
  modernMeaning: "Qaab-nidaam",
  example: "React is a frontend framework.",
  synonyms: ["structure"],
  isTech: true,
  explanationEn: "A pre-built platform or structure that developers use to build software applications.",
  explanationSo: "Madal ama dhismo hore loo diyaariyay oo horumariyayaashu isticmaalaan si ay barnaamijyada software-ka u dhisaan."
},
{
  id: 40,
  word: "deployment",
  language: "english",
  type: "noun",
  traditionalMeaning: "Soo-saarista Nidaamka",
  modernMeaning: "Daahfur-nidaam",
  example: "Deployment is successful.",
  synonyms: ["launch"],
  isTech: true,
  explanationEn: "The process of making a software application available for use in a live environment.",
  explanationSo: "Habka lagu samaynayo barnaamijka software-ka mid la heli karo oo ku hawlan deegaan nool."
},
{
  id: 41,
  word: "open source",
  language: "english",
  type: "noun",
  traditionalMeaning: "Il-furan",
  modernMeaning: "Furan-kood",
  example: "Linux is open source.",
  synonyms: ["public code"],
  isTech: true,
  explanationEn: "Software whose source code is freely available for anyone to view, modify, or distribute.",
  explanationSo: "Software oo koodkiisa isha si xor ah u heli karo qof kasta si uu u arko, u beddelo, ama u qaybsado."
},
{
  id: 42,
  word: "repository",
  language: "english",
  type: "noun",
  traditionalMeaning: "Kayd Kood",
  modernMeaning: "Kayd-kood",
  example: "Push the code to repository.",
  synonyms: ["repo"],
  isTech: true,
  explanationEn: "A storage location where source code and project files are managed and tracked.",
  explanationSo: "Meel kayd ah oo ay koodka isha iyo faylasha mashruuca lagu maamuul oo lagu raaco."
},
{
  id: 43,
  word: "version control",
  language: "english",
  type: "noun",
  traditionalMeaning: "Xakamaynta Noocyada",
  modernMeaning: "Nooc-maamul",
  example: "Git is a version control system.",
  synonyms: ["Git system"],
  isTech: true,
  explanationEn: "A system that records changes to files over time so you can recall specific versions later.",
  explanationSo: "Nidaam diiwaangeliya isbedelada faylasha waqti ka waqti si aad u soo ceshan karto noocyada gaar ah markii dambe."
},

{
  id: 44,
  word: "aabbe",
  language: "somali",
  type: "noun",
  traditionalMeaning: "father",
  modernMeaning: null,
  example: "Aabbahay waa shaqeeyaa.",
  synonyms: ["abbaha"],
  isTech: false,
  explanationEn: "A male parent; the father of a child.",
  explanationSo: "Waa aabbaha lab ah ee cunugga; mid ka mid ah waalidiinta."
},
{
  id: 45,
  word: "hooyo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "mother",
  modernMeaning: null,
  example: "Hooyaday waa naxariis badan.",
  synonyms: ["ummo"],
  isTech: false,
  explanationEn: "A female parent; the mother of a child.",
  explanationSo: "Waa hooyada dheddig ah ee cunugga; mid ka mid ah waalidiinta."
},
{
  id: 46,
  word: "wiil",
  language: "somali",
  type: "noun",
  traditionalMeaning: "boy / son",
  modernMeaning: null,
  example: "Wiilku waa ciyaarayaa.",
  synonyms: ["inan"],
  isTech: false,
  explanationEn: "A male child; a young boy or a son.",
  explanationSo: "Waa ilmo lab ah; wiil yar ama inan."
},
{
  id: 47,
  word: "gabar",
  language: "somali",
  type: "noun",
  traditionalMeaning: "girl / daughter",
  modernMeaning: null,
  example: "Gabartu waa waxbaranaysaa.",
  synonyms: ["inanad"],
  isTech: false,
  explanationEn: "A female child; a young girl or a daughter.",
  explanationSo: "Waa ilmo dheddig ah; gabar yar ama inanad."
},
{
  id: 48,
  word: "cunto",
  language: "somali",
  type: "noun",
  traditionalMeaning: "food",
  modernMeaning: null,
  example: "Cuntadu waa diyaar.",
  synonyms: ["raashin"],
  isTech: false,
  explanationEn: "Any nutritious substance that people eat to maintain life and growth.",
  explanationSo: "Wax kasta oo nafaqo leh oo dadku cunaan si ay u noolaadaan oo ay u koraanina."
},
{
  id: 49,
  word: "cabitaan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "drink / beverage",
  modernMeaning: null,
  example: "Cabitaanka waa qabow.",
  synonyms: ["shanbaar"],
  isTech: false,
  explanationEn: "Any liquid that a person drinks, such as water, juice, or tea.",
  explanationSo: "Dareer kasta oo qof cabbo, sida biyo, casiir, ama shaah."
},
{
  id: 50,
  word: "suuq",
  language: "somali",
  type: "noun",
  traditionalMeaning: "market",
  modernMeaning: null,
  example: "Waxaan aaday suuqa.",
  synonyms: ["ganacsi"],
  isTech: false,
  explanationEn: "A place where goods are bought and sold; a marketplace or commercial centre.",
  explanationSo: "Goob ay badeecado lagu iibsado lana iibiyo; suuq ama xarun ganacsi."
},
{
  id: 51,
  word: "magaalo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "city",
  modernMeaning: null,
  example: "Magaaladu waa mashquul.",
  synonyms: ["degmo"],
  isTech: false,
  explanationEn: "A large town or urban area where many people live and work.",
  explanationSo: "Degmo weyn ama aag magaalo ah oo dadku badan ay ku nool yihiin oo ku shaqeeyaan."
},
{
  id: 52,
  word: "dal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "country / nation",
  modernMeaning: null,
  example: "Dalkeygu waa qurux badan.",
  synonyms: ["wadan"],
  isTech: false,
  explanationEn: "A nation or territory identified as a distinct political entity with its own government.",
  explanationSo: "Wadan ama dhul loo aqoonsan yahay sida hay'ad siyaasadeed gooni ah oo dowlad u leh."
},
{
  id: 53,
  word: "xoolo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "livestock / animals",
  modernMeaning: null,
  example: "Xooluhu waa hanti.",
  synonyms: ["duunyo nool"],
  isTech: false,
  explanationEn: "Domesticated animals kept on a farm or by a family, especially cattle, sheep, and goats.",
  explanationSo: "Xayawaanka guri-la-dhaqay ee xero ama qoys haysto, gaar ahaan lo', ido, iyo ri'."
},
{
  id: 54,
  word: "qof",
  language: "somali",
  type: "noun",
  traditionalMeaning: "person",
  modernMeaning: null,
  example: "Qof walba waa muhiim.",
  synonyms: ["ruux"],
  isTech: false,
  explanationEn: "A human being regarded as an individual.",
  explanationSo: "Aadane la arko sidii shakhsi gooni ah."
},
{
  id: 55,
  word: "jacayl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "love",
  modernMeaning: null,
  example: "Jacaylku waa qurux.",
  synonyms: ["kal-gacal"],
  isTech: false,
  explanationEn: "A deep feeling of affection and care towards another person.",
  explanationSo: "Dareen qoto dheer oo jecel iyo daryeel leh oo u jira qof kale."
},
{
  id: 56,
  word: "saaxiib",
  language: "somali",
  type: "noun",
  traditionalMeaning: "friend",
  modernMeaning: null,
  example: "Saaxiibkay waa daacad.",
  synonyms: ["rafiiq"],
  isTech: false,
  explanationEn: "A person whom one knows well and has a bond of mutual affection with.",
  explanationSo: "Qof la yaqaan oo xiriir jaceyl iyo is-xurmo ah lala leeyahay."
},
{
  id: 57,
  word: "cadceed",
  language: "somali",
  type: "noun",
  traditionalMeaning: "sun",
  modernMeaning: null,
  example: "Cadceeddu way iftiintaa.",
  synonyms: ["qorrax"],
  isTech: false,
  explanationEn: "The star at the centre of the solar system that provides light and heat to Earth.",
  explanationSo: "Xiddigta ku taal bartamaha nidaamka qorraxda oo iftiinka iyo kulaylka dhulka siisa."
},
{
  id: 58,
  word: "dayax",
  language: "somali",
  type: "noun",
  traditionalMeaning: "moon",
  modernMeaning: null,
  example: "Dayaxu waa qurux badan.",
  synonyms: [],
  isTech: false,
  explanationEn: "The natural satellite of Earth that orbits the planet and reflects sunlight.",
  explanationSo: "Dayaxa dabiiciga ah ee Dunida wareegaa oo iftiinka qorraxda xidaa."
},
{
  id: 59,
  word: "roob",
  language: "somali",
  type: "noun",
  traditionalMeaning: "rain",
  modernMeaning: null,
  example: "Roob ayaa da'aya.",
  synonyms: [],
  isTech: false,
  explanationEn: "Water that falls from clouds in the sky as small liquid drops.",
  explanationSo: "Biyo ka soo da'a daruuraha cirka sida dhibicyo yaryar oo dareereed ah."
},
{
  id: 60,
  word: "dab",
  language: "somali",
  type: "noun",
  traditionalMeaning: "fire",
  modernMeaning: null,
  example: "Dabku waa kulul.",
  synonyms: [],
  isTech: false,
  explanationEn: "The rapid combustion of material producing heat, light, and flame.",
  explanationSo: "Gubasho xawli ah oo walxo u geysata kulaylka, iftiinka, iyo dab-weynaha."
},
{
  id: 61,
  word: "hawl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "task / work",
  modernMeaning: null,
  example: "Hawsha waa la qabtay.",
  synonyms: ["shaqo"],
  isTech: false,
  explanationEn: "A piece of work or a task that requires effort to complete.",
  explanationSo: "Wax shaqo ah ama hawl u baahan dadaal si loo dhammaystiro."
},
{
  id: 62,
  word: "shaqo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "job / work",
  modernMeaning: null,
  example: "Waxaan raadinayaa shaqo.",
  synonyms: ["hawl"],
  isTech: false,
  explanationEn: "Activity involving mental or physical effort done to achieve a purpose or earn income.",
  explanationSo: "Hawl maskax ama jir ah oo la qabanayo si loo gaaro ujeedo ama dakhli."
},
{
  id: 63,
  word: "waqti",
  language: "somali",
  type: "noun",
  traditionalMeaning: "time",
  modernMeaning: null,
  example: "Waqtigu waa qaali.",
  synonyms: [],
  isTech: false,
  explanationEn: "The indefinite continued progress of existence and events; time as measured in hours, days, or years.",
  explanationSo: "Soccodka joogtada ah ee jiritaanka iyo dhacdooyinka; wakhtiga xisaabta saacadaha, maalinta, ama sanadka."
},


{
  id: 64,
  word: "ability",
  language: "english",
  type: "noun",
  traditionalMeaning: "kartida",
  modernMeaning: null,
  example: "She has the ability to lead.",
  synonyms: ["skill", "capacity"],
  isTech: false,
  explanationEn: "The power or skill to do something.",
  explanationSo: "Awoodda ama xirfadda qof u leh in uu wax qabto."
},
{
  id: 65,
  word: "access",
  language: "english",
  type: "noun",
  traditionalMeaning: "gelitaan",
  modernMeaning: null,
  example: "You have access to the system.",
  synonyms: ["entry", "permission"],
  isTech: false,
  explanationEn: "The right or ability to enter, use, or obtain something.",
  explanationSo: "Xuquuqda ama awoodda lagu galo, lagu isticmaalo, ama wax la helo."
},
{
  id: 66,
  word: "account",
  language: "english",
  type: "noun",
  traditionalMeaning: "akoonti",
  modernMeaning: null,
  example: "Create a new account.",
  synonyms: ["profile"],
  isTech: false,
  explanationEn: "A record of financial transactions; or a personal profile on a digital platform.",
  explanationSo: "Diiwaanka macaamilaadka dhaqaalaha; ama profile shakhsi ah oo madal dijitaal ah."
},
{
  id: 67,
  word: "achievement",
  language: "english",
  type: "noun",
  traditionalMeaning: "guul",
  modernMeaning: null,
  example: "Graduation is a big achievement.",
  synonyms: ["success", "accomplishment"],
  isTech: false,
  explanationEn: "A thing successfully accomplished, especially through effort or skill.",
  explanationSo: "Wax si guul leh loo qabto, gaar ahaan iyada oo loo marayo dadaal ama xirfad."
},
{
  id: 68,
  word: "action",
  language: "english",
  type: "noun",
  traditionalMeaning: "ficil",
  modernMeaning: null,
  example: "Take action immediately.",
  synonyms: ["act", "move"],
  isTech: false,
  explanationEn: "The process of doing something to achieve an aim.",
  explanationSo: "Habka la qabanayo si loo gaaro hadaf."
},
{
  id: 69,
  word: "activity",
  language: "english",
  type: "noun",
  traditionalMeaning: "hawl",
  modernMeaning: null,
  example: "Outdoor activity is healthy.",
  synonyms: ["task", "event"],
  isTech: false,
  explanationEn: "A thing that a person or group does or has done.",
  explanationSo: "Wax qof ama koox samayso ama samaysay."
},
{
  id: 70,
  word: "addition",
  language: "english",
  type: "noun",
  traditionalMeaning: "isku-darid",
  modernMeaning: null,
  example: "Addition is basic math.",
  synonyms: ["sum"],
  isTech: false,
  explanationEn: "The process of adding numbers together; also the act of including something extra.",
  explanationSo: "Habka lagu kordhinayo tirooyinka is-ku-dhafan; sidoo kale ficilka ku-darista wax dheeraad ah."
},
{
  id: 71,
  word: "address",
  language: "english",
  type: "noun",
  traditionalMeaning: "cinwaan",
  modernMeaning: null,
  example: "Write your address here.",
  synonyms: ["location"],
  isTech: false,
  explanationEn: "The details of the place where someone lives or an organisation is situated.",
  explanationSo: "Faahfaahinta goobta qof ku noolyahay ama hay'ad ku taallo."
},
{
  id: 72,
  word: "advice",
  language: "english",
  type: "noun",
  traditionalMeaning: "talo",
  modernMeaning: null,
  example: "He gave me good advice.",
  synonyms: ["guidance"],
  isTech: false,
  explanationEn: "Guidance or recommendations offered with regard to a course of action.",
  explanationSo: "Hagitaan ama talo la bixiyo oo la xiriira tallaabada la qaadanayo."
},
{
  id: 73,
  word: "agreement",
  language: "english",
  type: "noun",
  traditionalMeaning: "heshiis",
  modernMeaning: null,
  example: "They signed an agreement.",
  synonyms: ["contract", "deal"],
  isTech: false,
  explanationEn: "Harmony of opinion or a legally binding arrangement between two or more parties.",
  explanationSo: "Is-waafaqsanaanta ra'yiga ama qandaraas sharciyeysan oo u dhexeeya laba ama ka badan oo dhinacyo ah."
},
{
  id: 74,
  word: "air",
  language: "english",
  type: "noun",
  traditionalMeaning: "hawo",
  modernMeaning: null,
  example: "Fresh air is important.",
  synonyms: [],
  isTech: false,
  explanationEn: "The invisible mixture of gases surrounding the Earth, which all living things breathe.",
  explanationSo: "Isku-dhafka hawada aan la arki karin ee adduunka ku hareeraysan, oo noolaha oo dhan neef qaataan."
},
{
  id: 75,
  word: "analysis",
  language: "english",
  type: "noun",
  traditionalMeaning: "falanqayn",
  modernMeaning: null,
  example: "Data analysis is essential.",
  synonyms: ["examination"],
  isTech: false,
  explanationEn: "The detailed examination of something to understand its structure or meaning.",
  explanationSo: "Baaritaanka faahfaahsan ee wax si loo fahmo dhismihiisa ama macnahiisa."
},
{
  id: 76,
  word: "answer",
  language: "english",
  type: "noun",
  traditionalMeaning: "jawaab",
  modernMeaning: null,
  example: "What is the answer?",
  synonyms: ["response"],
  isTech: false,
  explanationEn: "A response to a question or problem.",
  explanationSo: "Jawaabta su'aal ama dhibaato."
},
{
  id: 77,
  word: "application",
  language: "english",
  type: "noun",
  traditionalMeaning: "codsi",
  modernMeaning: null,
  example: "Submit your job application.",
  synonyms: ["request", "form"],
  isTech: false,
  explanationEn: "A formal request; or a software program designed to perform specific tasks.",
  explanationSo: "Codsi rasmi ah; ama barnaamij software ah oo loogu talagalay hawlo gaar ah."
},
{
  id: 78,
  word: "area",
  language: "english",
  type: "noun",
  traditionalMeaning: "aag",
  modernMeaning: null,
  example: "This area is quiet.",
  synonyms: ["region", "zone"],
  isTech: false,
  explanationEn: "A region or part of a place, or the extent of a surface.",
  explanationSo: "Gobol ama qayb meel ah, ama ballaadha dusha."
},
{
  id: 79,
  word: "argument",
  language: "english",
  type: "noun",
  traditionalMeaning: "dood",
  modernMeaning: null,
  example: "They had an argument.",
  synonyms: ["debate"],
  isTech: false,
  explanationEn: "An exchange of opposing views; or a set of reasons used to support a conclusion.",
  explanationSo: "Wadahadal aragtiyaha ka soo horjeeda; ama jilbaha loo isticmaalo si loo taageero gabagabada."
},
{
  id: 80,
  word: "army",
  language: "english",
  type: "noun",
  traditionalMeaning: "ciidan",
  modernMeaning: null,
  example: "The army protects the country.",
  synonyms: ["military"],
  isTech: false,
  explanationEn: "An organised military force equipped for fighting on land.",
  explanationSo: "Ciidan nidaamsan oo hubaysan oo dhulka ku dagaalamaya."
},
{
  id: 81,
  word: "art",
  language: "english",
  type: "noun",
  traditionalMeaning: "farshaxan",
  modernMeaning: null,
  example: "Art expresses emotion.",
  synonyms: ["creativity"],
  isTech: false,
  explanationEn: "Creative works expressing human imagination and skill, such as painting or sculpture.",
  explanationSo: "Shaqooyinka hal-abuurka ah ee muujinaya maskaxda iyo xirfadda aadanaha, sida sawirka ama saameynta."
},
{
  id: 82,
  word: "attack",
  language: "english",
  type: "noun",
  traditionalMeaning: "weerar",
  modernMeaning: null,
  example: "The city faced an attack.",
  synonyms: ["assault"],
  isTech: false,
  explanationEn: "An aggressive and violent act against a person or place.",
  explanationSo: "Ficil xoog ah oo cadaawad leh oo loo geystaa qof ama goob."
},
{
  id: 83,
  word: "attention",
  language: "english",
  type: "noun",
  traditionalMeaning: "feejignaan",
  modernMeaning: null,
  example: "Pay attention in class.",
  synonyms: ["focus"],
  isTech: false,
  explanationEn: "The act of focusing the mind on something.",
  explanationSo: "Ficilka maskaxda wax ku diiraddeynta."
}, 


{
  id: 84,
  word: "xog-ururin",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data collection",
  modernMeaning: "Data Gathering System",
  example: "Shirkaddu waxay sameysay xog-ururin cusub.",
  synonyms: ["ururin xog"],
  isTech: true,
  explanationEn: "The systematic gathering of information for analysis or storage.",
  explanationSo: "Uruurinta nidaamsan ee macluumaadka si loo falanqeeyo ama loo kaydiyay."
},
{
  id: 85,
  word: "xog-falanqayn",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data analysis",
  modernMeaning: "Analytics Engine",
  example: "Xog-falanqayn ayaa muhiim u ah ganacsiga.",
  synonyms: ["falanqayn xog"],
  isTech: true,
  explanationEn: "The detailed examination of data to discover patterns and draw conclusions.",
  explanationSo: "Baaritaanka faahfaahsan ee xogta si loo helo qaababka oo gabagabo laga soo saaro."
},
{
  id: 86,
  word: "xog-maamul",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data management",
  modernMeaning: "Data Control",
  example: "Xog-maamul wanaagsan ayaa kordhiya amniga.",
  synonyms: [],
  isTech: true,
  explanationEn: "The process of organising, maintaining, and securing data effectively.",
  explanationSo: "Habka lagu nidaaminayo, la daryeelayo, oo la ilaaliya xogta si waxtar leh."
},
{
  id: 87,
  word: "sir-xog",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data encryption",
  modernMeaning: "Secure Data Layer",
  example: "Sir-xog ayaa ilaalisa xogta isticmaalaha.",
  synonyms: ["siraynta xogta"],
  isTech: true,
  explanationEn: "The conversion of data into an unreadable format to protect it from unauthorised access.",
  explanationSo: "Rogidda xogta qaab aan la aqrin karin si looga ilaaliyo gelitaanka aan la oggolayn."
},
{
  id: 88,
  word: "aqoonsi-Danabeysan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital identity",
  modernMeaning: "Digital ID",
  example: "Aqoonsi-dijitaal ayaa loo baahan yahay.",
  synonyms: [],
  isTech: true,
  explanationEn: "A digital representation of a person's identity used online or in electronic systems.",
  explanationSo: "Muujinta aqoonsiga danabeysan qofka ee onlaynka ama nidaamyada elektaroonig lagu isticmaalo."
},
{
  id: 89,
  word: "lacag-Danabeysan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital money",
  modernMeaning: "E-currency",
  example: "Lacag-dijitaal ayaa ku faaftay Afrika.",
  synonyms: [],
  isTech: true,
  explanationEn: "Money that exists only in electronic form and is used for online transactions.",
  explanationSo: "Lacagta kaliya ee qaab elektaroonig ah ku jirta oo loogu isticmaalo macaamiladaha onlaynka."
},
{
  id: 90,
  word: "Ganacsi -danabeysan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "online business",
  modernMeaning: "E-commerce",
  example: "Ganacsi-dijitaal waa mustaqbalka.",
  synonyms: [],
  isTech: true,
  explanationEn: "Commercial transactions or business activities conducted over the internet.",
  explanationSo: "Macaamiladaha ganacsiga ama hawlaha ganacsiga ee loo maro internet-ka."
},
{
  id: 91,
  word: "barnaamij-mobil",
  language: "somali",
  type: "noun",
  traditionalMeaning: "mobile application",
  modernMeaning: "Mobile App",
  example: "Waxaan dhisnay barnaamij-mobil cusub.",
  synonyms: [],
  isTech: true,
  explanationEn: "A software application designed to run on a mobile device such as a smartphone.",
  explanationSo: "Barnaamijka software-ka loo sameeyay si uu ku shaqeeyo qalab gacanta sida taleefanka casriga ah."
},
{
  id: 92,
  word: "kood-qoris",
  language: "somali",
  type: "noun",
  traditionalMeaning: "coding",
  modernMeaning: "Software Development",
  example: "Kood-qoris waa xirfad muhiim ah.",
  synonyms: ["barnaamijsi"],
  isTech: true,
  explanationEn: "The activity of writing instructions in a programming language to create software.",
  explanationSo: "Hawsha qorista tilmaamaha luqadda barnaamijyada si loo abuuro software."
},
{
  id: 93,
  word: "keyd-daruurid",
  language: "somali",
  type: "noun",
  traditionalMeaning: "cloud computing",
  modernMeaning: "Cloud System",
  example: "Keyd-daruurid ayaa fududeysa kaydinta.",
  synonyms: [],
  isTech: true,
  explanationEn: "Using remote servers hosted on the internet to store, manage, and process data.",
  explanationSo: "Isticmaalka server-yada fog ee internet ku marsan si loo kaydiyaw, lo maamulo, oo xog loo hawlgeliyo."
},
{
  id: 94,
  word: "Aminga-internetka",
  language: "somali",
  type: "noun",
  traditionalMeaning: "cybersecurity",
  modernMeaning: "Digital Security",
  example: "Aminga-internetka waa muhiim.",
  synonyms: [],
  isTech: true,
  explanationEn: "Protecting digital information, devices, and networks from cyber threats.",
  explanationSo: "Ilaalinta macluumaadka danabeysan, qalabka, iyo shabakadaha halbowlaha cyber-ka."
},
{
  id: 95,
  word: "xiriir-shabakad",
  language: "somali",
  type: "noun",
  traditionalMeaning: "network connection",
  modernMeaning: "Network Link",
  example: "Xiriir-shabakad ayaa go'ay.",
  synonyms: [],
  isTech: true,
  explanationEn: "The link or pathway enabling devices to communicate within a network.",
  explanationSo: "Xididdada ama jidka u oggolaanaya qalabka in ay xiriiraan shabakad gudahood."
},
{
  id: 96,
  word: "qalab-caqli",
  language: "somali",
  type: "noun",
  traditionalMeaning: "smart device",
  modernMeaning: "Smart Device",
  example: "Qalab-caqli ayaa fududeeya nolosha.",
  synonyms: [],
  isTech: true,
  explanationEn: "An electronic device that uses computing technology to perform smart functions.",
  explanationSo: "Qalab elektaroonig ah oo isticmaala teknoolojiyada kombiyuutarka si uu hawlo caqli-gal ah u qabto."
},
{
  id: 97,
  word: "robot-hawl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "automation robot",
  modernMeaning: "Automation Bot",
  example: "Robot-hawl ayaa qabtay shaqada.",
  synonyms: [],
  isTech: true,
  explanationEn: "Automated machinery or software that performs repetitive tasks without human input.",
  explanationSo: "Mashiinnada ama software-ka tooska ah ee qaabila hawlaha soo-noqnoqda aan gelitaanka aadanaha lahayn."
},
{
  id: 98,
  word: "xog-kayd",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data storage",
  modernMeaning: "Storage System",
  example: "Xog-kayd ayaa buuxsamay.",
  synonyms: [],
  isTech: true,
  explanationEn: "A system or device used to store digital data for later use.",
  explanationSo: "Nidaam ama qalab loo isticmaalo kaydinta xogta dijitaalka si markii danbe loo isticmaalo."
},
{
  id: 99,
  word: "muuqaal-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital media",
  modernMeaning: "Digital Media",
  example: "Muuqaal-dijitaal ayaa si dhakhso ah u faafa.",
  synonyms: [],
  isTech: true,
  explanationEn: "Audio-visual content in a digital format shared online or through digital devices.",
  explanationSo: "Xog muqaal-dhegood ah oo qaab dijitaal ah oo la wadaago onlaynka ama iyada oo loo marayo qalabka dijitaalka."
},
{
  id: 100,
  word: "cod-bixinta-onlayn",
  language: "somali",
  type: "noun",
  traditionalMeaning: "online voting",
  modernMeaning: "E-voting",
  example: "Cod-bixinta-onlayn waa mustaqbalka doorashooyinka.",
  synonyms: [],
  isTech: true,
  explanationEn: "A system that allows voters to cast their votes electronically via the internet.",
  explanationSo: "Nidaam u oggolaanaya codbixiyayaasha in ay cod onlaynka iyada oo loo marayo internet bixiyaan."
},
{
  id: 101,
  word: "sir-fure",
  language: "somali",
  type: "noun",
  traditionalMeaning: "password",
  modernMeaning: "Passkey",
  example: "Ha la wadaagin sir-fure.",
  synonyms: [],
  isTech: true,
  explanationEn: "A secret combination of characters used to gain access to a system or account.",
  explanationSo: "Isku-dar sir ah oo lagu galo nidaam ama akoonti."
},
{
  id: 102,
  word: "fariin-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital message",
  modernMeaning: "E-message",
  example: "Fariin-dijitaal ayaa la diray.",
  synonyms: [],
  isTech: true,
  explanationEn: "A message sent or received through electronic means such as email or instant messaging.",
  explanationSo: "Fariin la diray ama la helay iyada oo loo marayo hab elektaroonig sida email ama farriin degdeg ah."
},
{
  id: 103,
  word: "madal-bulsho",
  language: "somali",
  type: "noun",
  traditionalMeaning: "social platform",
  modernMeaning: "Social Network",
  example: "Madal-bulsho ayaa isku xirta dadka.",
  synonyms: [],
  isTech: true,
  explanationEn: "An online platform where people create profiles and share content with others.",
  explanationSo: "Madal onlayn ah oo dadku ku sameeystaan profile oo ay nuxurka kale ula wadaagaan."
},


{
  id: 104,
  word: "caafimaad",
  language: "somali",
  type: "noun",
  traditionalMeaning: "health",
  modernMeaning: null,
  example: "Caafimaadku waa nimco.",
  synonyms: ["fayoobi"],
  isTech: false,
  explanationEn: "The state of being free from illness or injury; physical and mental well-being.",
  explanationSo: "Xaalada ka madax banaan jirrada ama dhaawaca; caafimaadka jirka iyo maskaxda."
},
{
  id: 105,
  word: "cudur",
  language: "somali",
  type: "noun",
  traditionalMeaning: "disease / illness",
  modernMeaning: null,
  example: "Cudurka waa la daawayn karaa.",
  synonyms: ["xanuun"],
  isTech: false,
  explanationEn: "An illness that affects the body or mind with specific symptoms.",
  explanationSo: "Jirrad jirka ama maskaxda saameysata oo calaamado gaar ah leh."
},
{
  id: 106,
  word: "xanuun",
  language: "somali",
  type: "noun",
  traditionalMeaning: "pain",
  modernMeaning: null,
  example: "Waxaan dareemayaa xanuun madax.",
  synonyms: ["cudur"],
  isTech: false,
  explanationEn: "A feeling of physical discomfort or suffering caused by injury or illness.",
  explanationSo: "Dareen xanuun jireed ah oo sabab u ah dhaawac ama jirrad."
},
{
  id: 107,
  word: "daawo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "medicine",
  modernMeaning: null,
  example: "Daawada waqtigeeda qaado.",
  synonyms: ["dawo"],
  isTech: false,
  explanationEn: "A substance used to treat or prevent disease and relieve pain.",
  explanationSo: "Walax loo isticmaalo si loo daaweeyo ama looga hortago cudur iyo xanuun."
},
{
  id: 108,
  word: "dhakhtar",
  language: "somali",
  type: "noun",
  traditionalMeaning: "doctor",
  modernMeaning: null,
  example: "Dhakhtarku wuu ku baari doonaa.",
  synonyms: [],
  isTech: false,
  explanationEn: "A qualified medical professional trained to diagnose and treat illness.",
  explanationSo: "Xirfadle caafimaad oo tababaran ogaanshaha iyo daaweynta cudurrada."
},
{
  id: 109,
  word: "kalkaaliye",
  language: "somali",
  type: "noun",
  traditionalMeaning: "nurse",
  modernMeaning: null,
  example: "Kalkaaliyaha ayaa daryeela bukaanka.",
  synonyms: [],
  isTech: false,
  explanationEn: "A trained healthcare professional who provides care and support to patients.",
  explanationSo: "Xirfadle caafimaad oo tababaran oo daryeelka iyo taageerada bukaanka bixiya."
},
{
  id: 110,
  word: "isbitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "hospital",
  modernMeaning: null,
  example: "Waxaan aaday isbitaalka.",
  synonyms: [],
  isTech: false,
  explanationEn: "A place where sick or injured people receive medical treatment and care.",
  explanationSo: "Goob ay qof bukaan ah ama dhaawacmay ku helo daaweyn iyo daryeel caafimaad."
},
{
  id: 111,
  word: "bukaan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "patient",
  modernMeaning: null,
  example: "Bukaanku wuxuu sugayaa dhakhtarka.",
  synonyms: [],
  isTech: false,
  explanationEn: "A person receiving medical treatment; someone who is ill or injured.",
  explanationSo: "Qof daaweyn caafimaad qabanaya; mid bukaan ah ama dhaawacmay."
},
{
  id: 112,
  word: "qalliinka",
  language: "somali",
  type: "noun",
  traditionalMeaning: "surgery",
  modernMeaning: null,
  example: "Qalliinka waa lagu guuleystay.",
  synonyms: [],
  isTech: false,
  explanationEn: "A medical operation in which a doctor cuts into the body to treat a condition.",
  explanationSo: "Hawlgal caafimaad oo dhakhtar jirka ku galo si uu xaalad u daaweeyo."
},
{
  id: 113,
  word: "dhiig",
  language: "somali",
  type: "noun",
  traditionalMeaning: "blood",
  modernMeaning: null,
  example: "Dhiig badan ayaa lumay.",
  synonyms: [],
  isTech: false,
  explanationEn: "The red fluid that circulates through the body, carrying oxygen and nutrients.",
  explanationSo: "Dareeraha casaan ah ee jirka ku socdaa, oo qaada oksijiinta iyo nafaqada."
},
{
  id: 114,
  word: "wadne",
  language: "somali",
  type: "noun",
  traditionalMeaning: "heart",
  modernMeaning: null,
  example: "Wadnuhu waa xubinta ugu muhiimsan.",
  synonyms: [],
  isTech: false,
  explanationEn: "The muscular organ in the chest that pumps blood through the body.",
  explanationSo: "Xubinta muruqyada leh ee laabta ku jirta ee dhiigga jirka ku riixda."
},
{
  id: 115,
  word: "maskax",
  language: "somali",
  type: "noun",
  traditionalMeaning: "brain",
  modernMeaning: null,
  example: "Maskaxdu waxay xakameysaa jirka.",
  synonyms: [],
  isTech: false,
  explanationEn: "The organ inside the skull that controls thought, memory, and body functions.",
  explanationSo: "Xubin madaxa ku jirta oo xukumta fikirka, xusuusta, iyo hawlaha jirka."
},
{
  id: 116,
  word: "sambab",
  language: "somali",
  type: "noun",
  traditionalMeaning: "lung",
  modernMeaning: null,
  example: "Sambabku wuxuu qaataa hawada.",
  synonyms: [],
  isTech: false,
  explanationEn: "Either of the two organs in the chest used for breathing and exchanging oxygen.",
  explanationSo: "Mid ka mid ah laba xubnood oo laabta ku jira oo loo isticmaalo neefta iyo is-beddelka oksijiinta."
},
{
  id: 117,
  word: "beer",
  language: "somali",
  type: "noun",
  traditionalMeaning: "liver",
  modernMeaning: null,
  example: "Beerku waa muhiim jirka.",
  synonyms: [],
  isTech: false,
  explanationEn: "The large organ in the abdomen that processes nutrients and filters blood.",
  explanationSo: "Xubin weyn oo caloosha ku jirta oo nafaqada hawlgelisa oo dhiigga sifeeysa."
},
{
  id: 118,
  word: "kilyo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "kidney",
  modernMeaning: null,
  example: "Kilyaha ayaa sifeeya dhiigga.",
  synonyms: [],
  isTech: false,
  explanationEn: "Either of two bean-shaped organs that filter waste from the blood and produce urine.",
  explanationSo: "Mid ka mid ah laba xubnood oo qaanjada u eg oo wasakhda dhiigga ka sifeeysa oo kaadi sameysa."
},
{
  id: 119,
  word: "laf",
  language: "somali",
  type: "noun",
  traditionalMeaning: "bone",
  modernMeaning: null,
  example: "Laf ayaa jabtay.",
  synonyms: [],
  isTech: false,
  explanationEn: "Any of the hard pieces that form the skeleton of the body.",
  explanationSo: "Wax kasta oo adag oo ka sameeya lafaha jirka."
},
{
  id: 120,
  word: "maqaarka",
  language: "somali",
  type: "noun",
  traditionalMeaning: "skin",
  modernMeaning: null,
  example: "Maqaarku waa difaac.",
  synonyms: [],
  isTech: false,
  explanationEn: "The outer layer of the body that covers and protects internal organs.",
  explanationSo: "Lakabka dibadda ee jirka oo daboola oo ilaaliya xubnahaas gudaha."
},
{
  id: 121,
  word: "indho",
  language: "somali",
  type: "noun",
  traditionalMeaning: "eyes",
  modernMeaning: null,
  example: "Indhaha ayaan wax ku arkaa/araga.",
  synonyms: [],
  isTech: false,
  explanationEn: "The organs of sight, used for seeing.",
  explanationSo: "Xubnahaas aragga, loo isticmaalo arista."
},
{
  id: 122,
  word: "san",
  language: "somali",
  type: "noun",
  traditionalMeaning: "nose",
  modernMeaning: null,
  example: "San ayaa xirmay.",
  synonyms: [],
  isTech: false,
  explanationEn: "The organ on the face used for smelling and breathing.",
  explanationSo: "Xubinta wejiiga ku taal oo loo isticmaalo urta iyo neefta."
},
{
  id: 123,
  word: "dheg",
  language: "somali",
  type: "noun",
  traditionalMeaning: "ear",
  modernMeaning: null,
  example: "Dheg ayaa xanuunaysa.",
  synonyms: [],
  isTech: false,
  explanationEn: "The organ used for hearing sounds.",
  explanationSo: "Xubin loo isticmaalo maqlidda codadka."
},


{
  id: 124,
  word: "infection",
  language: "english",
  type: "noun",
  traditionalMeaning: "caabuq",
  modernMeaning: null,
  example: "The infection spread quickly.",
  synonyms: ["contamination"],
  isTech: false,
  explanationEn: "The invasion and multiplication of harmful microorganisms in the body causing disease.",
  explanationSo: "Galitaanka iyo kobcidda miraha la-dhicis ah ee jirka keena cudur."
},
{
  id: 125,
  word: "inflammation",
  language: "english",
  type: "noun",
  traditionalMeaning: "barar",
  modernMeaning: null,
  example: "The inflammation caused pain.",
  synonyms: ["swelling"],
  isTech: false,
  explanationEn: "A localised physical condition where part of the body becomes red, swollen, and painful.",
  explanationSo: "Xaalad jireed oo maxalli ah oo qaybta jirka ka casaan, bararsan, oo xanuunaysa."
},
{
  id: 126,
  word: "fever",
  language: "english",
  type: "noun",
  traditionalMeaning: "qandho",
  modernMeaning: null,
  example: "He has a high fever.",
  synonyms: ["high temperature"],
  isTech: false,
  explanationEn: "A body temperature that is higher than normal, usually indicating an infection.",
  explanationSo: "Heerkulka jirka ka sareeysa caadiga, badanaa tilmaama caabuq."
},
{
  id: 127,
  word: "headache",
  language: "english",
  type: "noun",
  traditionalMeaning: "madax-xanuun",
  modernMeaning: null,
  example: "She suffers from headache.",
  synonyms: [],
  isTech: false,
  explanationEn: "A continuous pain felt in the head.",
  explanationSo: "Xanuun joogto ah oo madaxa lagu dareemo."
},
{
  id: 128,
  word: "diabetes",
  language: "english",
  type: "noun",
  traditionalMeaning: "sonkorow",
  modernMeaning: null,
  example: "Diabetes requires careful monitoring.",
  synonyms: [],
  isTech: false,
  explanationEn: "A metabolic disease in which the body cannot properly regulate blood sugar levels.",
  explanationSo: "Cudur metabolism ah oo jirku ku xukumi karin heerka sonkorowga dhiigga."
},
{
  id: 129,
  word: "hypertension",
  language: "english",
  type: "noun",
  traditionalMeaning: "dhiig-karka",
  modernMeaning: null,
  example: "Hypertension affects the heart.",
  synonyms: ["high blood pressure"],
  isTech: false,
  explanationEn: "A medical condition where the force of blood against artery walls is persistently high.",
  explanationSo: "Xaalad caafimaad oo xoogga dhiigga jiirka dhiigga ka joogto ah oo sarreeya."
},
{
  id: 130,
  word: "fracture",
  language: "english",
  type: "noun",
  traditionalMeaning: "jab",
  modernMeaning: null,
  example: "The fracture needs treatment.",
  synonyms: ["broken bone"],
  isTech: false,
  explanationEn: "A crack or break in a bone.",
  explanationSo: "Jabka ama dillaaca lafta."
},
{
  id: 131,
  word: "cancer",
  language: "english",
  type: "noun",
  traditionalMeaning: "kansar",
  modernMeaning: null,
  example: "Cancer treatment is improving.",
  synonyms: ["malignancy"],
  isTech: false,
  explanationEn: "A disease caused by uncontrolled growth of abnormal cells in the body.",
  explanationSo: "Cudur ku sabab ah koridda xukun-la'aanta ee unugyada aan caadiga ahayn ee jirka."
},
{
  id: 132,
  word: "virus",
  language: "english",
  type: "noun",
  traditionalMeaning: "fayras",
  modernMeaning: null,
  example: "The virus spreads fast.",
  synonyms: [],
  isTech: false,
  explanationEn: "A microscopic infectious agent that replicates inside living cells and causes disease.",
  explanationSo: "Laan-dheer caabuq ah oo aad u yar ee unugyada nool gudahood ku baxa oo keena cudur."
},
{
  id: 133,
  word: "bacteria",
  language: "english",
  type: "noun",
  traditionalMeaning: "bakteeriya",
  modernMeaning: null,
  example: "Bacteria can cause disease.",
  synonyms: [],
  isTech: false,
  explanationEn: "Microscopic single-celled organisms, some of which can cause disease in humans.",
  explanationSo: "Nool yaryar oo hal-unug ah, qaar ka mid ahi cudur aadanaha ku keeni karaan."
},
{
  id: 134,
  word: "allergy",
  language: "english",
  type: "noun",
  traditionalMeaning: "xasaasiyad",
  modernMeaning: null,
  example: "He has a peanut allergy.",
  synonyms: [],
  isTech: false,
  explanationEn: "An abnormal immune response to a substance that is harmless to most people.",
  explanationSo: "Jawaab difaac aan caadi ahayn ee walxaha ay ku jirto inta badan dadka aafooda ah."
},
{
  id: 135,
  word: "asthma",
  language: "english",
  type: "noun",
  traditionalMeaning: "neef",
  modernMeaning: null,
  example: "Asthma affects breathing.",
  synonyms: [],
  isTech: false,
  explanationEn: "A chronic condition affecting the airways, making breathing difficult.",
  explanationSo: "Xaalad joogto ah oo neefta saameysata, neefta adag keenta."
},
{
  id: 136,
  word: "anemia",
  language: "english",
  type: "noun",
  traditionalMeaning: "dhiig-yaraan",
  modernMeaning: null,
  example: "Anemia causes weakness.",
  synonyms: [],
  isTech: false,
  explanationEn: "A condition where there is a deficiency of red blood cells or haemoglobin.",
  explanationSo: "Xaalad ay ku jirto yarida unugyada dhiigga cas ama haemoglobinka."
},
{
  id: 137,
  word: "pregnancy",
  language: "english",
  type: "noun",
  traditionalMeaning: "uur",
  modernMeaning: null,
  example: "Pregnancy requires care.",
  synonyms: [],
  isTech: false,
  explanationEn: "The period during which a woman carries a developing baby in her womb.",
  explanationSo: "Muddada ay haweenay uursato oo ay jirkeeda ku sitaa ilmaha kobcaya."
},
{
  id: 138,
  word: "vaccine",
  language: "english",
  type: "noun",
  traditionalMeaning: "tallaal",
  modernMeaning: null,
  example: "The vaccine prevents disease.",
  synonyms: ["immunization"],
  isTech: false,
  explanationEn: "A biological preparation that provides immunity against a specific disease.",
  explanationSo: "Daawo nooleed oo siinaysa difaaca cudur gaar ah."
},
{
  id: 139,
  word: "diagnosis",
  language: "english",
  type: "noun",
  traditionalMeaning: "ogaansho caafimaad",
  modernMeaning: null,
  example: "The diagnosis was accurate.",
  synonyms: [],
  isTech: false,
  explanationEn: "The identification of the nature of an illness through examination.",
  explanationSo: "Aqoonsiga nooca jirradda iyada oo loo marayo baaritaan."
},
{
  id: 140,
  word: "treatment",
  language: "english",
  type: "noun",
  traditionalMeaning: "daaweyn",
  modernMeaning: null,
  example: "Treatment started immediately.",
  synonyms: ["therapy"],
  isTech: false,
  explanationEn: "Medical care given to a patient for an illness or injury.",
  explanationSo: "Daryeel caafimaad oo la siinayo bukaan cudur ama dhaawac u leh."
},
{
  id: 141,
  word: "surgery",
  language: "english",
  type: "noun",
  traditionalMeaning: "qalliin",
  modernMeaning: null,
  example: "The surgery was successful.",
  synonyms: ["operation"],
  isTech: false,
  explanationEn: "Medical treatment involving cutting into the body to repair or remove tissue.",
  explanationSo: "Daaweyn caafimaad oo ku lug leh goynta jirka si loo saamiyo ama looga saaro unug."
},
{
  id: 142,
  word: "emergency",
  language: "english",
  type: "noun",
  traditionalMeaning: "xaalad degdeg ah",
  modernMeaning: null,
  example: "This is a medical emergency.",
  synonyms: [],
  isTech: false,
  explanationEn: "A serious, unexpected situation requiring immediate action.",
  explanationSo: "Xaalad adag oo aan la filanayn oo u baahan tallaabo degdeg ah."
},
{
  id: 143,
  word: "ambulance",
  language: "english",
  type: "noun",
  traditionalMeaning: "gaari gurmad",
  modernMeaning: null,
  example: "Call the ambulance quickly.",
  synonyms: [],
  isTech: false,
  explanationEn: "A vehicle equipped to carry sick or injured people to hospital.",
  explanationSo: "Gaari ugu habboon qaadista bukaan ama dhaawacsan oo isbitaalka geeysa."
},


{
  id: 144,
  word: "cardiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga wadnaha",
  modernMeaning: null,
  example: "Cardiology focuses on heart diseases.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that deals with diseases and disorders of the heart.",
  explanationSo: "Laanka daawada ee ku takhasusay cudurrada iyo xaaladaha wadnaha."
},
{
  id: 145,
  word: "neurology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga neerfaha",
  modernMeaning: null,
  example: "Neurology studies the nervous system.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine concerned with the study and treatment of the nervous system.",
  explanationSo: "Laanka daawada ee ku shaqeeya cilmiga iyo daaweynta nidaamka neerfaha."
},
{
  id: 146,
  word: "dermatology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga maqaarka",
  modernMeaning: null,
  example: "Dermatology treats skin conditions.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine dealing with the diagnosis and treatment of skin conditions.",
  explanationSo: "Laanka daawada ku takhasusay ogaanshaha iyo daaweynta xaaladaha maqaarka."
},
{
  id: 147,
  word: "orthopedics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga lafaha",
  modernMeaning: null,
  example: "Orthopedics deals with bone injuries.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that corrects deformities and treats disorders of bones and muscles.",
  explanationSo: "Laanka daawada ee sax-sameeya cilladaha iyo daaweeya xaaladaha lafaha iyo muruqyada."
},
{
  id: 148,
  word: "pediatrics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga carruurta",
  modernMeaning: null,
  example: "Pediatrics treats children.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine dealing with the health and medical care of children.",
  explanationSo: "Laanka daawada ku takhasusay caafimaadka iyo daaweynta carruurta."
},
{
  id: 149,
  word: "gynecology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga haweenka",
  modernMeaning: null,
  example: "Gynecology focuses on women’s health.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine dealing with the functions and diseases of women's reproductive system.",
  explanationSo: "Laanka daawada ku takhasusay hawlaha iyo cudurrada nidaamka taranka haweenka."
},
{
  id: 150,
  word: "psychiatry",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga maskaxda iyo dhimirka",
  modernMeaning: null,
  example: "Psychiatry treats mental disorders.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that deals with mental illness and behavioral disorders.",
  explanationSo: "Laanka daawada ku takhasusay jirrada maskaxda iyo qaloocinimada dhaqanka."
},
{
  id: 151,
  word: "radiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga raajada",
  modernMeaning: null,
  example: "Radiology uses imaging technology.",
  synonyms: [],
  isTech: false,
  explanationEn: "The science of using imaging technology to diagnose and treat diseases.",
  explanationSo: "Cilmiga isticmaalaya teknoolojiyada sawir-qaadista si loo ogaado oo loo daaweeyo cudurrada."
},
{
  id: 152,
  word: "anesthesia",
  language: "english",
  type: "noun",
  traditionalMeaning: "suuxdin caafimaad",
  modernMeaning: null,
  example: "Anesthesia prevents pain during surgery.",
  synonyms: [],
  isTech: false,
  explanationEn: "The use of medication to block sensation and pain during medical procedures.",
  explanationSo: "Isticmaalka daawada si loo xanibo dareemida iyo xanuunka muddada hawlgalada caafimaad."
},
{
  id: 153,
  word: "pathology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga cudurrada",
  modernMeaning: null,
  example: "Pathology studies disease causes.",
  synonyms: [],
  isTech: false,
  explanationEn: "The science of the causes and effects of diseases, especially as examined in a laboratory.",
  explanationSo: "Cilmiga sababaha iyo saameynta cudurrada, gaar ahaan sida baaritaanka shaybaarka lagu ogaado."
},
{
  id: 154,
  word: "epidemiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga faafidda cudurrada",
  modernMeaning: null,
  example: "Epidemiology tracks disease outbreaks.",
  synonyms: [],
  isTech: false,
  explanationEn: "The study of how diseases spread and can be controlled in populations.",
  explanationSo: "Cilmiga sida cudurrada dadka ugu faafa lana xukumi karo ee bulshada."
},
{
  id: 155,
  word: "oncology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kansarka",
  modernMeaning: null,
  example: "Oncology treats cancer patients.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that specialises in the study and treatment of cancer.",
  explanationSo: "Laanka daawada ku takhasusay cilmiga iyo daaweynta kansarka."
},
{
  id: 156,
  word: "immunology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga difaaca jirka",
  modernMeaning: null,
  example: "Immunology studies immune responses.",
  synonyms: [],
  isTech: false,
  explanationEn: "The study of the immune system and its role in protecting the body from disease.",
  explanationSo: "Cilmiga nidaamka difaaca jirka iyo doorka uu ka qaata ilaalinta jirka cudurrada ka."
},
{
  id: 157,
  word: "hematology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga dhiigga",
  modernMeaning: null,
  example: "Hematology examines blood disorders.",
  synonyms: [],
  isTech: false,
  explanationEn: "The study of blood, blood-forming organs, and blood diseases.",
  explanationSo: "Cilmiga dhiigga, xubnahaas sameeya dhiigga, iyo cudurrada dhiigga."
},
{
  id: 158,
  word: "nephrology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kilyaha",
  modernMeaning: null,
  example: "Nephrology treats kidney diseases.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that focuses on the diagnosis and treatment of kidney diseases.",
  explanationSo: "Waax/Qeyb kamida daaweynta iyo ku takhasuska cudurrada kilyaha."
},
{
  id: 159,
  word: "pulmonology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga Neefta iyo sambabada",
  modernMeaning: null,
  example: "Pulmonology deals with lung disorders.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that focuses on diseases and conditions of the respiratory system, including the lungs.",
  explanationSo: "Waax kamida daaweynta iyo ku takhasuska cudurrada iyo xaaladaha nidaamka neefsashada, oo ay ku jiraan sambabada."
},
{
  id: 160,
  word: "gastroenterology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga caloosha iyo mindhicirka",
  modernMeaning: null,
  example: "Gastroenterology treats digestive diseases.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine focused on the digestive system and its disorders.",
  explanationSo: "Wax kamida daaweynta ama ku takhasusay nidaamka dheef-shiidka iyo cudurradiisa."
},
{
  id: 161,
  word: "urology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kaadi-mareenka",
  modernMeaning: null,
  example: "Urology focuses on urinary system.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine concerned with the urinary system and male reproductive organs.",
  explanationSo: "Laanka daawada ku takhasusay nidaamka kaadi-mareenka iyo xubnahaas taranka lab."
},
{
  id: 162,
  word: "obstetrics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga dhalmada",
  modernMeaning: null,
  example: "Obstetrics manages pregnancy and childbirth.",
  synonyms: [],
  isTech: false,
  explanationEn: "The branch of medicine that deals with pregnancy, childbirth, and the postpartum period.",
  explanationSo: "Laanka daawada ku takhasusay uurka, dhalmada, iyo xilliga kadib dhalashada."
},

{
  id: 163,
  word: "rehabilitation",
  language: "english",
  type: "noun",
  traditionalMeaning: "soo kabasho",
  modernMeaning: null,
  example: "Rehabilitation helps recovery.",
  synonyms: [],
  isTech: false,
  explanationEn: "The process of helping someone recover and regain health or normal life after illness or injury.",
  explanationSo: "Habka lagu caawiyo qof in uu soo kabtaa oo uu ku soo laabto caafimaad ama nolosha caadiga ah kadib jirrad ama dhaawac."
},
{
  id: 164,
  word: "Dropout",
  language: "english",
  type: "noun",
  traditionalMeaning: "Dhicis",
  modernMeaning: null,
  example: "The student became a dropout.",
  synonyms: [],
  isTech: false,
  explanationEn: "A person who has left school or a programme before completing it.",
  explanationSo: "Qof iskoolka ama barnaamijka ka baxay kahor intuusan dhammayn."
},
{
  id: 165,
  word: "Dhicis",
  language: "somali",
  type: "noun",
  traditionalMeaning: "dropout",
  modernMeaning: null,
  example: "Ardeygi imtixaanki ayu dhacey, dhulka ayaan ku dhacey.",
  synonyms: [],
  isTech: false,
  explanationEn: "Someone who leaves school or a program before completing it.",
  explanationSo: "Qof iskoolka ama Taclin ka baxay kahor intuusan dhammayn."
},
{
  id: 166,
  word: "Aamus",
  language: "somali",
  type: "noun",
  traditionalMeaning: "Silence",
  modernMeaning: null,
  example: "Waan aamusay markii aan maqlo wararka xun.",
  synonyms: [],
  isTech: false,
  explanationEn: "The complete absence of sound or noise; a state of quiet.",
  explanationSo: "Maqnaanshaha cod ama buuq gebi ahaanba; xaalad degganan ah."
},
{
  id: 167,
  word: "Aniga",
  language: "somali",
  type: "pronoun",
  traditionalMeaning: "Me/I",
  modernMeaning: null,
  example: "Aniga ayaa jeclaa inaan barto luqadaha.",
  synonyms: [],
  isTech: false,
  explanationEn: "The pronoun used by a speaker to refer to themselves.",
  explanationSo: "Erayga loo isticmaalo hadalka si uu qofku naftiisa ugu tilmaamo."
},
{
  id: 168,
  word: "Asaga",
  language: "somali",
  type: "pronoun",
  traditionalMeaning: "He/Him",
  modernMeaning: null,
  example: "Asaga ayaa iga caawiyay shaqada.",
  synonyms: [],
  isTech: false,
  explanationEn: "The pronoun used by a speaker to refer to someone else.",
  explanationSo: "Erayga loo isticmaalo hadalka si uu qofku qof kale u tilmaamo."
},

];