const dictionary = [
  // Somali → English words
  {
    id: 1,
    word: "buug",
    language: "somali",
    type: "noun",
    traditionalMeaning: "book",
    modernMeaning: null,
    example: "Buugga waa mid fiican.",
    synonyms: ["qoraal", "buugaag"],
    isTech: false
  },
  {
    id: 2,
    word: "guri",
    language: "somali",
    type: "noun",
    traditionalMeaning: "house / home",
    modernMeaning: null,
    example: "Gurigaygu waa weyn yahay.",
    synonyms: ["hoy", "meel deganaanshaha"],
    isTech: false
  },
  {
    id: 3,
    word: "biyo",
    language: "somali",
    type: "noun",
    traditionalMeaning: "water",
    modernMeaning: null,
    example: "Biyaha badda waa cusbo.",
    synonyms: ["roob (rain water)"],
    isTech: false
  },
  {
    id: 4,
    word: "nabad",
    language: "somali",
    type: "noun",
    traditionalMeaning: "peace / greeting",
    modernMeaning: null,
    example: "Nabad iyo nolol.",
    synonyms: ["xasilloon", "aamaanshaha"],
    isTech: false
  },
  {
    id: 5,
    word: "waxbarasho",
    language: "somali",
    type: "noun",
    traditionalMeaning: "education / learning",
    modernMeaning: null,
    example: "Waxbarashaду waa muhiim.",
    synonyms: ["tacliim", "barashada"],
    isTech: false
  },
  {
    id: 6,
    word: "dhul",
    language: "somali",
    type: "noun",
    traditionalMeaning: "land / earth / ground",
    modernMeaning: null,
    example: "Dhulku waa mid qurxoon.",
    synonyms: ["carrada", "aduunka"],
    isTech: false
  },
  {
    id: 7,
    word: "xidid",
    language: "somali",
    type: "noun",
    traditionalMeaning: "root / origin",
    modernMeaning: null,
    example: "Xididkaygu waa Soomaaliya.",
    synonyms: ["asalka", "abtirsiinyo"],
    isTech: false
  },
  {
    id: 8,
    word: "feker",
    language: "somali",
    type: "noun",
    traditionalMeaning: "thought / idea",
    modernMeaning: null,
    example: "Fekerkaaga waa fiican yahay.",
    synonyms: ["fikrad", "aragti"],
    isTech: false
  },

  // English → Somali words
  {
    id: 9,
    word: "knowledge",
    language: "english",
    type: "noun",
    traditionalMeaning: "aqoon",
    modernMeaning: null,
    example: "Knowledge is power — Aqoontu waa awoodda.",
    synonyms: ["information", "wisdom", "understanding"],
    isTech: false
  },
  {
    id: 10,
    word: "language",
    language: "english",
    type: "noun",
    traditionalMeaning: "luqad",
    modernMeaning: null,
    example: "Somali is a beautiful language.",
    synonyms: ["tongue", "dialect", "speech"],
    isTech: false
  },
  {
    id: 11,
    word: "science",
    language: "english",
    type: "noun",
    traditionalMeaning: "sayniska",
    modernMeaning: null,
    example: "Science helps us understand the world.",
    synonyms: ["research", "study"],
    isTech: false
  },
  {
    id: 12,
    word: "culture",
    language: "english",
    type: "noun",
    traditionalMeaning: "dhaqan",
    modernMeaning: null,
    example: "Somali culture is rich and diverse.",
    synonyms: ["tradition", "heritage", "civilization"],
    isTech: false
  },

  // Tech Words
  {
    id: 13,
    word: "artificial intelligence",
    language: "english",
    type: "noun",
    traditionalMeaning: "Caqliga Macmalka ah",
    modernMeaning: "Caqli",
    example: "Artificial intelligence is changing the world.",
    synonyms: ["AI", "machine learning", "deep learning"],
    isTech: true
  },
  {
    id: 14,
    word: "algorithm",
    language: "english",
    type: "noun",
    traditionalMeaning: "Qaacidada Xisaabinta",
    modernMeaning: "Qaacido",
    example: "Search engines use algorithms to rank results.",
    synonyms: ["procedure", "process", "formula"],
    isTech: true
  },
  {
    id: 15,
    word: "programming",
    language: "english",
    type: "noun",
    traditionalMeaning: "Barnaamijyeynta Kombiyuutarka",
    modernMeaning: "Barnaamijsi",
    example: "Programming is the language of the future.",
    synonyms: ["coding", "software development"],
    isTech: true
  },
  {
    id: 16,
    word: "database",
    language: "english",
    type: "noun",
    traditionalMeaning: "Kaydka Xogta",
    modernMeaning: "Kayd-xog",
    example: "The database stores millions of records.",
    synonyms: ["data store", "repository"],
    isTech: true
  },
  {
    id: 17,
    word: "internet",
    language: "english",
    type: "noun",
    traditionalMeaning: "Shabakadda Adduunka",
    modernMeaning: "Xarig",
    example: "The internet connects the world.",
    synonyms: ["web", "network", "online"],
    isTech: true
  },
  {
    id: 18,
    word: "cybersecurity",
    language: "english",
    type: "noun",
    traditionalMeaning: "Amniga Teknoolojiyada",
    modernMeaning: "Amni-xarig",
    example: "Cybersecurity protects your digital life.",
    synonyms: ["digital security", "information security"],
    isTech: true
  },
  {
    id: 19,
    word: "cloud computing",
    language: "english",
    type: "noun",
    traditionalMeaning: "Xisaabinta Daruuraha Dhanka Teknoolojiyada",
    modernMeaning: "Daruuro-xisaab",
    example: "Cloud computing enables remote work.",
    synonyms: ["cloud storage", "SaaS", "remote computing"],
    isTech: true
  },
  {
    id: 20,
    word: "blockchain",
    language: "english",
    type: "noun",
    traditionalMeaning: "Xidmada Silsilad Xogeed",
    modernMeaning: "Silsilad-xog",
    example: "Blockchain powers cryptocurrencies.",
    synonyms: ["distributed ledger", "crypto"],
    isTech: true
  },
  {
    id: 21,
    word: "software",
    language: "english",
    type: "noun",
    traditionalMeaning: "Barnaamijka Kombiyuutarka",
    modernMeaning: "Nidaam-kombiyuutar",
    example: "This software is open source.",
    synonyms: ["program", "application", "app"],
    isTech: true
  },

  {
    id: 22,
    word: "robot",
    language: "english",
    type: "noun",
    traditionalMeaning: "Mishiinka Aadanaha La Mid ah",
    modernMeaning: "Mishiin-aadane",
    example: "Robots are used in manufacturing.",
    synonyms: ["automaton", "android", "machine"],
    isTech: true
  },
  {
    id: 23,
    word: "Sakariye",
    language: "Somali",
    type: "Person/ Shakhsi",
    traditionalMeaning: "Khabiir Kombiyuutar Sare ahna aaqoonyahan iyo aasaasaha shirkadda MakersLab",
    modernMeaning: "Zakarie idiris",
    example: "Sakariye waa aasaasaha shirkadda MakersLab.",
  },
  {
  id: 24,
  word: "startup",
  language: "english",
  type: "noun",
  traditionalMeaning: "Shirkad Cusub",
  modernMeaning: "Bilow-ganacsi",
  example: "He launched a tech startup in 2026.",
  synonyms: ["new company", "venture"],
  isTech: true
},
{
  id: 25,
  word: "innovation",
  language: "english",
  type: "noun",
  traditionalMeaning: "Hal-abuur",
  modernMeaning: "Abuur-cusub",
  example: "Innovation drives progress.",
  synonyms: ["creativity", "invention"],
  isTech: true
},
{
  id: 26,
  word: "data",
  language: "english",
  type: "noun",
  traditionalMeaning: "Xog",
  modernMeaning: "Xog",
  example: "Data is the new oil.",
  synonyms: ["information", "records"],
  isTech: true
},
{
  id: 27,
  word: "server",
  language: "english",
  type: "noun",
  traditionalMeaning: "Adeege Kombiyuutar",
  modernMeaning: "Adeeg-xog",
  example: "The server is down.",
  synonyms: ["host", "backend machine"],
  isTech: true
},
{
  id: 28,
  word: "frontend",
  language: "english",
  type: "noun",
  traditionalMeaning: "Qaybta Hore ee Nidaamka",
  modernMeaning: "Hore-nidaam",
  example: "He works as a frontend developer.",
  synonyms: ["UI side", "client side"],
  isTech: true
},
{
  id: 29,
  word: "backend",
  language: "english",
  type: "noun",
  traditionalMeaning: "Qaybta Dambe ee Nidaamka",
  modernMeaning: "Dambe-nidaam",
  example: "Backend handles database logic.",
  synonyms: ["server side"],
  isTech: true
},
{
  id: 30,
  word: "API",
  language: "english",
  type: "noun",
  traditionalMeaning: "Isku-xirka Barnaamijyada",
  modernMeaning: "Xiriir-nidaam",
  example: "The app connects using an API.",
  synonyms: ["interface", "endpoint"],
  isTech: true
},
{
  id: 31,
  word: "encryption",
  language: "english",
  type: "noun",
  traditionalMeaning: "Siraynta Xogta",
  modernMeaning: "Sir-xog",
  example: "Encryption protects user data.",
  synonyms: ["data protection"],
  isTech: true
},
{
  id: 32,
  word: "authentication",
  language: "english",
  type: "noun",
  traditionalMeaning: "Hubinta Aqoonsiga",
  modernMeaning: "Hubin-aqoonsi",
  example: "Two-factor authentication is secure.",
  synonyms: ["verification"],
  isTech: true
},
{
  id: 33,
  word: "biometric",
  language: "english",
  type: "noun",
  traditionalMeaning: "Aqoonsiga Jirka",
  modernMeaning: "Jir-aqoonsi",
  example: "Biometric login uses fingerprint.",
  synonyms: ["fingerprint ID"],
  isTech: true
},
{
  id: 34,
  word: "machine learning",
  language: "english",
  type: "noun",
  traditionalMeaning: "Barashada Mashiinka",
  modernMeaning: "Baro-mashiin",
  example: "Machine learning improves predictions.",
  synonyms: ["ML"],
  isTech: true
},
{
  id: 35,
  word: "user interface",
  language: "english",
  type: "noun",
  traditionalMeaning: "Isdhexgalka Isticmaalaha",
  modernMeaning: "Arag-dhexgal",
  example: "The user interface is clean.",
  synonyms: ["UI"],
  isTech: true
},
{
  id: 36,
  word: "user experience",
  language: "english",
  type: "noun",
  traditionalMeaning: "Khibradda Isticmaalaha",
  modernMeaning: "Khibrad-isticmaal",
  example: "Good UX increases engagement.",
  synonyms: ["UX"],
  isTech: true
},
{
  id: 37,
  word: "bug",
  language: "english",
  type: "noun",
  traditionalMeaning: "Khalad Barnaamij",
  modernMeaning: "Cilad-kood",
  example: "There is a bug in the system.",
  synonyms: ["error"],
  isTech: true
},
{
  id: 38,
  word: "debugging",
  language: "english",
  type: "noun",
  traditionalMeaning: "Sixidda Khaladaadka",
  modernMeaning: "Cilad-saar",
  example: "Debugging takes time.",
  synonyms: ["fixing errors"],
  isTech: true
},
{
  id: 39,
  word: "framework",
  language: "english",
  type: "noun",
  traditionalMeaning: "Qaab-dhismeed Barnaamij",
  modernMeaning: "Qaab-nidaam",
  example: "React is a frontend framework.",
  synonyms: ["structure"],
  isTech: true
},
{
  id: 40,
  word: "deployment",
  language: "english",
  type: "noun",
  traditionalMeaning: "Soo-saarista Nidaamka",
  modernMeaning: "Daahfur-nidaam",
  example: "Deployment is successful.",
  synonyms: ["launch"],
  isTech: true
},
{
  id: 41,
  word: "open source",
  language: "english",
  type: "noun",
  traditionalMeaning: "Il-furan",
  modernMeaning: "Furan-kood",
  example: "Linux is open source.",
  synonyms: ["public code"],
  isTech: true
},
{
  id: 42,
  word: "repository",
  language: "english",
  type: "noun",
  traditionalMeaning: "Kayd Kood",
  modernMeaning: "Kayd-kood",
  example: "Push the code to repository.",
  synonyms: ["repo"],
  isTech: true
},
{
  id: 43,
  word: "version control",
  language: "english",
  type: "noun",
  traditionalMeaning: "Xakamaynta Noocyada",
  modernMeaning: "Nooc-maamul",
  example: "Git is a version control system.",
  synonyms: ["Git system"],
  isTech: true
},

{
  id: 44,
  word: "aabbe",
  language: "somali",
  type: "noun",
  traditionalMeaning: "father",
  modernMeaning: null,
  example: "Aabbahay waa shaqeeyaa.",
  synonyms: ["abbaha"],
  isTech: false
},
{
  id: 45,
  word: "hooyo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "mother",
  modernMeaning: null,
  example: "Hooyaday waa naxariis badan.",
  synonyms: ["ummo"],
  isTech: false
},
{
  id: 46,
  word: "wiil",
  language: "somali",
  type: "noun",
  traditionalMeaning: "boy / son",
  modernMeaning: null,
  example: "Wiilku waa ciyaarayaa.",
  synonyms: ["inan"],
  isTech: false
},
{
  id: 47,
  word: "gabar",
  language: "somali",
  type: "noun",
  traditionalMeaning: "girl / daughter",
  modernMeaning: null,
  example: "Gabartu waa waxbaranaysaa.",
  synonyms: ["inanad"],
  isTech: false
},
{
  id: 48,
  word: "cunto",
  language: "somali",
  type: "noun",
  traditionalMeaning: "food",
  modernMeaning: null,
  example: "Cuntadu waa diyaar.",
  synonyms: ["raashin"],
  isTech: false
},
{
  id: 49,
  word: "cabitaan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "drink / beverage",
  modernMeaning: null,
  example: "Cabitaanka waa qabow.",
  synonyms: ["shanbaar"],
  isTech: false
},
{
  id: 50,
  word: "suuq",
  language: "somali",
  type: "noun",
  traditionalMeaning: "market",
  modernMeaning: null,
  example: "Waxaan aaday suuqa.",
  synonyms: ["ganacsi"],
  isTech: false
},
{
  id: 51,
  word: "magaalo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "city",
  modernMeaning: null,
  example: "Magaaladu waa mashquul.",
  synonyms: ["degmo"],
  isTech: false
},
{
  id: 52,
  word: "dal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "country / nation",
  modernMeaning: null,
  example: "Dalkeygu waa qurux badan.",
  synonyms: ["wadan"],
  isTech: false
},
{
  id: 53,
  word: "xoolo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "livestock / animals",
  modernMeaning: null,
  example: "Xooluhu waa hanti.",
  synonyms: ["duunyo nool"],
  isTech: false
},
{
  id: 54,
  word: "qof",
  language: "somali",
  type: "noun",
  traditionalMeaning: "person",
  modernMeaning: null,
  example: "Qof walba waa muhiim.",
  synonyms: ["ruux"],
  isTech: false
},
{
  id: 55,
  word: "jacayl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "love",
  modernMeaning: null,
  example: "Jacaylku waa qurux.",
  synonyms: ["kal-gacal"],
  isTech: false
},
{
  id: 56,
  word: "saaxiib",
  language: "somali",
  type: "noun",
  traditionalMeaning: "friend",
  modernMeaning: null,
  example: "Saaxiibkay waa daacad.",
  synonyms: ["rafiiq"],
  isTech: false
},
{
  id: 57,
  word: "cadceed",
  language: "somali",
  type: "noun",
  traditionalMeaning: "sun",
  modernMeaning: null,
  example: "Cadceeddu way iftiintaa.",
  synonyms: ["qorrax"],
  isTech: false
},
{
  id: 58,
  word: "dayax",
  language: "somali",
  type: "noun",
  traditionalMeaning: "moon",
  modernMeaning: null,
  example: "Dayaxu waa qurux badan.",
  synonyms: [],
  isTech: false
},
{
  id: 59,
  word: "roob",
  language: "somali",
  type: "noun",
  traditionalMeaning: "rain",
  modernMeaning: null,
  example: "Roob ayaa da'aya.",
  synonyms: [],
  isTech: false
},
{
  id: 60,
  word: "dab",
  language: "somali",
  type: "noun",
  traditionalMeaning: "fire",
  modernMeaning: null,
  example: "Dabku waa kulul.",
  synonyms: [],
  isTech: false
},
{
  id: 61,
  word: "hawl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "task / work",
  modernMeaning: null,
  example: "Hawsha waa la qabtay.",
  synonyms: ["shaqo"],
  isTech: false
},
{
  id: 62,
  word: "shaqo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "job / work",
  modernMeaning: null,
  example: "Waxaan raadinayaa shaqo.",
  synonyms: ["hawl"],
  isTech: false
},
{
  id: 63,
  word: "waqti",
  language: "somali",
  type: "noun",
  traditionalMeaning: "time",
  modernMeaning: null,
  example: "Waqtigu waa qaali.",
  synonyms: [],
  isTech: false
},
// ===== SOMALI → ENGLISH PACK (Batch 2) =====

{
  id: 44,
  word: "aabbe",
  language: "somali",
  type: "noun",
  traditionalMeaning: "father",
  modernMeaning: null,
  example: "Aabbahay waa shaqeeyaa.",
  synonyms: ["abbaha"],
  isTech: false
},
{
  id: 45,
  word: "hooyo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "mother",
  modernMeaning: null,
  example: "Hooyaday waa naxariis badan.",
  synonyms: ["ummo"],
  isTech: false
},
{
  id: 46,
  word: "wiil",
  language: "somali",
  type: "noun",
  traditionalMeaning: "boy / son",
  modernMeaning: null,
  example: "Wiilku waa ciyaarayaa.",
  synonyms: ["inan"],
  isTech: false
},
{
  id: 47,
  word: "gabar",
  language: "somali",
  type: "noun",
  traditionalMeaning: "girl / daughter",
  modernMeaning: null,
  example: "Gabartu waa waxbaranaysaa.",
  synonyms: ["inanad"],
  isTech: false
},
{
  id: 48,
  word: "cunto",
  language: "somali",
  type: "noun",
  traditionalMeaning: "food",
  modernMeaning: null,
  example: "Cuntadu waa diyaar.",
  synonyms: ["raashin"],
  isTech: false
},
{
  id: 49,
  word: "cabitaan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "drink / beverage",
  modernMeaning: null,
  example: "Cabitaanka waa qabow.",
  synonyms: ["shanbaar"],
  isTech: false
},
{
  id: 50,
  word: "suuq",
  language: "somali",
  type: "noun",
  traditionalMeaning: "market",
  modernMeaning: null,
  example: "Waxaan aaday suuqa.",
  synonyms: ["ganacsi"],
  isTech: false
},
{
  id: 51,
  word: "magaalo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "city",
  modernMeaning: null,
  example: "Magaaladu waa mashquul.",
  synonyms: ["degmo"],
  isTech: false
},
{
  id: 52,
  word: "dal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "country / nation",
  modernMeaning: null,
  example: "Dalkeygu waa qurux badan.",
  synonyms: ["wadan"],
  isTech: false
},
{
  id: 53,
  word: "xoolo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "livestock / animals",
  modernMeaning: null,
  example: "Xooluhu waa hanti.",
  synonyms: ["duunyo nool"],
  isTech: false
},
{
  id: 54,
  word: "qof",
  language: "somali",
  type: "noun",
  traditionalMeaning: "person",
  modernMeaning: null,
  example: "Qof walba waa muhiim.",
  synonyms: ["ruux"],
  isTech: false
},
{
  id: 55,
  word: "jacayl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "love",
  modernMeaning: null,
  example: "Jacaylku waa qurux.",
  synonyms: ["kal-gacal"],
  isTech: false
},
{
  id: 56,
  word: "saaxiib",
  language: "somali",
  type: "noun",
  traditionalMeaning: "friend",
  modernMeaning: null,
  example: "Saaxiibkay waa daacad.",
  synonyms: ["rafiiq"],
  isTech: false
},
{
  id: 57,
  word: "cadceed",
  language: "somali",
  type: "noun",
  traditionalMeaning: "sun",
  modernMeaning: null,
  example: "Cadceeddu way iftiintaa.",
  synonyms: ["qorrax"],
  isTech: false
},
{
  id: 58,
  word: "dayax",
  language: "somali",
  type: "noun",
  traditionalMeaning: "moon",
  modernMeaning: null,
  example: "Dayaxu waa qurux badan.",
  synonyms: [],
  isTech: false
},
{
  id: 59,
  word: "roob",
  language: "somali",
  type: "noun",
  traditionalMeaning: "rain",
  modernMeaning: null,
  example: "Roob ayaa da'aya.",
  synonyms: [],
  isTech: false
},
{
  id: 60,
  word: "dab",
  language: "somali",
  type: "noun",
  traditionalMeaning: "fire",
  modernMeaning: null,
  example: "Dabku waa kulul.",
  synonyms: [],
  isTech: false
},
{
  id: 61,
  word: "hawl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "task / work",
  modernMeaning: null,
  example: "Hawsha waa la qabtay.",
  synonyms: ["shaqo"],
  isTech: false
},
{
  id: 62,
  word: "shaqo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "job / work",
  modernMeaning: null,
  example: "Waxaan raadinayaa shaqo.",
  synonyms: ["hawl"],
  isTech: false
},
{
  id: 63,
  word: "waqti",
  language: "somali",
  type: "noun",
  traditionalMeaning: "time",
  modernMeaning: null,
  example: "Waqtigu waa qaali.",
  synonyms: [],
  isTech: false
}, 
// ===== ENGLISH → SOMALI PACK (Batch 1) =====

{
  id: 64,
  word: "ability",
  language: "english",
  type: "noun",
  traditionalMeaning: "kartida",
  modernMeaning: null,
  example: "She has the ability to lead.",
  synonyms: ["skill", "capacity"],
  isTech: false
},
{
  id: 65,
  word: "access",
  language: "english",
  type: "noun",
  traditionalMeaning: "gelitaan",
  modernMeaning: null,
  example: "You have access to the system.",
  synonyms: ["entry", "permission"],
  isTech: false
},
{
  id: 66,
  word: "account",
  language: "english",
  type: "noun",
  traditionalMeaning: "akoonti",
  modernMeaning: null,
  example: "Create a new account.",
  synonyms: ["profile"],
  isTech: false
},
{
  id: 67,
  word: "achievement",
  language: "english",
  type: "noun",
  traditionalMeaning: "guul",
  modernMeaning: null,
  example: "Graduation is a big achievement.",
  synonyms: ["success", "accomplishment"],
  isTech: false
},
{
  id: 68,
  word: "action",
  language: "english",
  type: "noun",
  traditionalMeaning: "ficil",
  modernMeaning: null,
  example: "Take action immediately.",
  synonyms: ["act", "move"],
  isTech: false
},
{
  id: 69,
  word: "activity",
  language: "english",
  type: "noun",
  traditionalMeaning: "hawl",
  modernMeaning: null,
  example: "Outdoor activity is healthy.",
  synonyms: ["task", "event"],
  isTech: false
},
{
  id: 70,
  word: "addition",
  language: "english",
  type: "noun",
  traditionalMeaning: "isku-darid",
  modernMeaning: null,
  example: "Addition is basic math.",
  synonyms: ["sum"],
  isTech: false
},
{
  id: 71,
  word: "address",
  language: "english",
  type: "noun",
  traditionalMeaning: "cinwaan",
  modernMeaning: null,
  example: "Write your address here.",
  synonyms: ["location"],
  isTech: false
},
{
  id: 72,
  word: "advice",
  language: "english",
  type: "noun",
  traditionalMeaning: "talo",
  modernMeaning: null,
  example: "He gave me good advice.",
  synonyms: ["guidance"],
  isTech: false
},
{
  id: 73,
  word: "agreement",
  language: "english",
  type: "noun",
  traditionalMeaning: "heshiis",
  modernMeaning: null,
  example: "They signed an agreement.",
  synonyms: ["contract", "deal"],
  isTech: false
},
{
  id: 74,
  word: "air",
  language: "english",
  type: "noun",
  traditionalMeaning: "hawo",
  modernMeaning: null,
  example: "Fresh air is important.",
  synonyms: [],
  isTech: false
},
{
  id: 75,
  word: "analysis",
  language: "english",
  type: "noun",
  traditionalMeaning: "falanqayn",
  modernMeaning: null,
  example: "Data analysis is essential.",
  synonyms: ["examination"],
  isTech: false
},
{
  id: 76,
  word: "answer",
  language: "english",
  type: "noun",
  traditionalMeaning: "jawaab",
  modernMeaning: null,
  example: "What is the answer?",
  synonyms: ["response"],
  isTech: false
},
{
  id: 77,
  word: "application",
  language: "english",
  type: "noun",
  traditionalMeaning: "codsi",
  modernMeaning: null,
  example: "Submit your job application.",
  synonyms: ["request", "form"],
  isTech: false
},
{
  id: 78,
  word: "area",
  language: "english",
  type: "noun",
  traditionalMeaning: "aag",
  modernMeaning: null,
  example: "This area is quiet.",
  synonyms: ["region", "zone"],
  isTech: false
},
{
  id: 79,
  word: "argument",
  language: "english",
  type: "noun",
  traditionalMeaning: "dood",
  modernMeaning: null,
  example: "They had an argument.",
  synonyms: ["debate"],
  isTech: false
},
{
  id: 80,
  word: "army",
  language: "english",
  type: "noun",
  traditionalMeaning: "ciidan",
  modernMeaning: null,
  example: "The army protects the country.",
  synonyms: ["military"],
  isTech: false
},
{
  id: 81,
  word: "art",
  language: "english",
  type: "noun",
  traditionalMeaning: "farshaxan",
  modernMeaning: null,
  example: "Art expresses emotion.",
  synonyms: ["creativity"],
  isTech: false
},
{
  id: 82,
  word: "attack",
  language: "english",
  type: "noun",
  traditionalMeaning: "weerar",
  modernMeaning: null,
  example: "The city faced an attack.",
  synonyms: ["assault"],
  isTech: false
},
{
  id: 83,
  word: "attention",
  language: "english",
  type: "noun",
  traditionalMeaning: "feejignaan",
  modernMeaning: null,
  example: "Pay attention in class.",
  synonyms: ["focus"],
  isTech: false
}, 
// ===== MODERN SOMALI TECH PACK (Batch 1) =====

{
  id: 84,
  word: "xog-ururin",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data collection",
  modernMeaning: "Data Gathering System",
  example: "Shirkaddu waxay sameysay xog-ururin cusub.",
  synonyms: ["ururin xog"],
  isTech: true
},
{
  id: 85,
  word: "xog-falanqayn",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data analysis",
  modernMeaning: "Analytics Engine",
  example: "Xog-falanqayn ayaa muhiim u ah ganacsiga.",
  synonyms: ["falanqayn xog"],
  isTech: true
},
{
  id: 86,
  word: "xog-maamul",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data management",
  modernMeaning: "Data Control",
  example: "Xog-maamul wanaagsan ayaa kordhiya amniga.",
  synonyms: [],
  isTech: true
},
{
  id: 87,
  word: "sir-xog",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data encryption",
  modernMeaning: "Secure Data Layer",
  example: "Sir-xog ayaa ilaalisa xogta isticmaalaha.",
  synonyms: ["siraynta xogta"],
  isTech: true
},
{
  id: 88,
  word: "aqoonsi-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital identity",
  modernMeaning: "Digital ID",
  example: "Aqoonsi-dijitaal ayaa loo baahan yahay.",
  synonyms: [],
  isTech: true
},
{
  id: 89,
  word: "lacag-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital money",
  modernMeaning: "E-currency",
  example: "Lacag-dijitaal ayaa ku faaftay Afrika.",
  synonyms: [],
  isTech: true
},
{
  id: 90,
  word: "ganacsi-onlayn",
  language: "somali",
  type: "noun",
  traditionalMeaning: "online business",
  modernMeaning: "E-commerce",
  example: "Ganacsi-onlayn waa mustaqbalka.",
  synonyms: [],
  isTech: true
},
{
  id: 91,
  word: "barnaamij-mobil",
  language: "somali",
  type: "noun",
  traditionalMeaning: "mobile application",
  modernMeaning: "Mobile App",
  example: "Waxaan dhisnay barnaamij-mobil cusub.",
  synonyms: [],
  isTech: true
},
{
  id: 92,
  word: "kood-qoris",
  language: "somali",
  type: "noun",
  traditionalMeaning: "coding",
  modernMeaning: "Software Development",
  example: "Kood-qoris waa xirfad muhiim ah.",
  synonyms: ["barnaamijsi"],
  isTech: true
},
{
  id: 93,
  word: "xisaab-daruuro",
  language: "somali",
  type: "noun",
  traditionalMeaning: "cloud computing",
  modernMeaning: "Cloud System",
  example: "Xisaab-daruuro ayaa fududeysa kaydinta.",
  synonyms: [],
  isTech: true
},
{
  id: 94,
  word: "amni-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "cybersecurity",
  modernMeaning: "Digital Security",
  example: "Amni-dijitaal waa muhiim.",
  synonyms: [],
  isTech: true
},
{
  id: 95,
  word: "xiriir-shabakad",
  language: "somali",
  type: "noun",
  traditionalMeaning: "network connection",
  modernMeaning: "Network Link",
  example: "Xiriir-shabakad ayaa go'ay.",
  synonyms: [],
  isTech: true
},
{
  id: 96,
  word: "qalab-caqli",
  language: "somali",
  type: "noun",
  traditionalMeaning: "smart device",
  modernMeaning: "Smart Device",
  example: "Qalab-caqli ayaa fududeeya nolosha.",
  synonyms: [],
  isTech: true
},
{
  id: 97,
  word: "robot-hawl",
  language: "somali",
  type: "noun",
  traditionalMeaning: "automation robot",
  modernMeaning: "Automation Bot",
  example: "Robot-hawl ayaa qabtay shaqada.",
  synonyms: [],
  isTech: true
},
{
  id: 98,
  word: "xog-kayd",
  language: "somali",
  type: "noun",
  traditionalMeaning: "data storage",
  modernMeaning: "Storage System",
  example: "Xog-kayd ayaa buuxsamay.",
  synonyms: [],
  isTech: true
},
{
  id: 99,
  word: "muuqaal-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital media",
  modernMeaning: "Digital Media",
  example: "Muuqaal-dijitaal ayaa si dhakhso ah u faafa.",
  synonyms: [],
  isTech: true
},
{
  id: 100,
  word: "cod-bixinta-onlayn",
  language: "somali",
  type: "noun",
  traditionalMeaning: "online voting",
  modernMeaning: "E-voting",
  example: "Cod-bixinta-onlayn waa mustaqbalka doorashooyinka.",
  synonyms: [],
  isTech: true
},
{
  id: 101,
  word: "sir-fure",
  language: "somali",
  type: "noun",
  traditionalMeaning: "password",
  modernMeaning: "Passkey",
  example: "Ha la wadaagin sir-fure.",
  synonyms: [],
  isTech: true
},
{
  id: 102,
  word: "fariin-dijitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "digital message",
  modernMeaning: "E-message",
  example: "Fariin-dijitaal ayaa la diray.",
  synonyms: [],
  isTech: true
},
{
  id: 103,
  word: "madal-bulsho",
  language: "somali",
  type: "noun",
  traditionalMeaning: "social platform",
  modernMeaning: "Social Network",
  example: "Madal-bulsho ayaa isku xirta dadka.",
  synonyms: [],
  isTech: true
},
// ===== MEDICAL WORDS PACK (Batch 1) =====

{
  id: 104,
  word: "caafimaad",
  language: "somali",
  type: "noun",
  traditionalMeaning: "health",
  modernMeaning: null,
  example: "Caafimaadku waa nimco.",
  synonyms: ["fayoobi"],
  isTech: false
},
{
  id: 105,
  word: "cudur",
  language: "somali",
  type: "noun",
  traditionalMeaning: "disease / illness",
  modernMeaning: null,
  example: "Cudurka waa la daawayn karaa.",
  synonyms: ["xanuun"],
  isTech: false
},
{
  id: 106,
  word: "xanuun",
  language: "somali",
  type: "noun",
  traditionalMeaning: "pain",
  modernMeaning: null,
  example: "Waxaan dareemayaa xanuun madax.",
  synonyms: ["cudur"],
  isTech: false
},
{
  id: 107,
  word: "daawo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "medicine",
  modernMeaning: null,
  example: "Daawada waqtigeeda qaado.",
  synonyms: ["dawo"],
  isTech: false
},
{
  id: 108,
  word: "dhakhtar",
  language: "somali",
  type: "noun",
  traditionalMeaning: "doctor",
  modernMeaning: null,
  example: "Dhakhtarku wuu ku baari doonaa.",
  synonyms: [],
  isTech: false
},
{
  id: 109,
  word: "kalkaaliye",
  language: "somali",
  type: "noun",
  traditionalMeaning: "nurse",
  modernMeaning: null,
  example: "Kalkaaliyaha ayaa daryeela bukaanka.",
  synonyms: [],
  isTech: false
},
{
  id: 110,
  word: "isbitaal",
  language: "somali",
  type: "noun",
  traditionalMeaning: "hospital",
  modernMeaning: null,
  example: "Waxaan aaday isbitaalka.",
  synonyms: [],
  isTech: false
},
{
  id: 111,
  word: "bukaan",
  language: "somali",
  type: "noun",
  traditionalMeaning: "patient",
  modernMeaning: null,
  example: "Bukaanku wuxuu sugayaa dhakhtarka.",
  synonyms: [],
  isTech: false
},
{
  id: 112,
  word: "qalliinka",
  language: "somali",
  type: "noun",
  traditionalMeaning: "surgery",
  modernMeaning: null,
  example: "Qalliinka waa lagu guuleystay.",
  synonyms: [],
  isTech: false
},
{
  id: 113,
  word: "dhiig",
  language: "somali",
  type: "noun",
  traditionalMeaning: "blood",
  modernMeaning: null,
  example: "Dhiig badan ayaa lumay.",
  synonyms: [],
  isTech: false
},
{
  id: 114,
  word: "wadne",
  language: "somali",
  type: "noun",
  traditionalMeaning: "heart",
  modernMeaning: null,
  example: "Wadnuhu waa xubinta ugu muhiimsan.",
  synonyms: [],
  isTech: false
},
{
  id: 115,
  word: "maskax",
  language: "somali",
  type: "noun",
  traditionalMeaning: "brain",
  modernMeaning: null,
  example: "Maskaxdu waxay xakameysaa jirka.",
  synonyms: [],
  isTech: false
},
{
  id: 116,
  word: "sambab",
  language: "somali",
  type: "noun",
  traditionalMeaning: "lung",
  modernMeaning: null,
  example: "Sambabku wuxuu qaataa hawada.",
  synonyms: [],
  isTech: false
},
{
  id: 117,
  word: "beer",
  language: "somali",
  type: "noun",
  traditionalMeaning: "liver",
  modernMeaning: null,
  example: "Beerku waa muhiim jirka.",
  synonyms: [],
  isTech: false
},
{
  id: 118,
  word: "kilyo",
  language: "somali",
  type: "noun",
  traditionalMeaning: "kidney",
  modernMeaning: null,
  example: "Kilyaha ayaa sifeeya dhiigga.",
  synonyms: [],
  isTech: false
},
{
  id: 119,
  word: "laf",
  language: "somali",
  type: "noun",
  traditionalMeaning: "bone",
  modernMeaning: null,
  example: "Laf ayaa jabtay.",
  synonyms: [],
  isTech: false
},
{
  id: 120,
  word: "maqaarka",
  language: "somali",
  type: "noun",
  traditionalMeaning: "skin",
  modernMeaning: null,
  example: "Maqaarku waa difaac.",
  synonyms: [],
  isTech: false
},
{
  id: 121,
  word: "indho",
  language: "somali",
  type: "noun",
  traditionalMeaning: "eyes",
  modernMeaning: null,
  example: "Indhaha waa la baaray.",
  synonyms: [],
  isTech: false
},
{
  id: 122,
  word: "san",
  language: "somali",
  type: "noun",
  traditionalMeaning: "nose",
  modernMeaning: null,
  example: "San ayaa xirmay.",
  synonyms: [],
  isTech: false
},
{
  id: 123,
  word: "dheg",
  language: "somali",
  type: "noun",
  traditionalMeaning: "ear",
  modernMeaning: null,
  example: "Dheg ayaa xanuunaysa.",
  synonyms: [],
  isTech: false
},
// ===== MEDICAL ENGLISH → SOMALI PACK (Batch 1) =====

{
  id: 124,
  word: "infection",
  language: "english",
  type: "noun",
  traditionalMeaning: "caabuq",
  modernMeaning: null,
  example: "The infection spread quickly.",
  synonyms: ["contamination"],
  isTech: false
},
{
  id: 125,
  word: "inflammation",
  language: "english",
  type: "noun",
  traditionalMeaning: "barar",
  modernMeaning: null,
  example: "The inflammation caused pain.",
  synonyms: ["swelling"],
  isTech: false
},
{
  id: 126,
  word: "fever",
  language: "english",
  type: "noun",
  traditionalMeaning: "qandho",
  modernMeaning: null,
  example: "He has a high fever.",
  synonyms: ["high temperature"],
  isTech: false
},
{
  id: 127,
  word: "headache",
  language: "english",
  type: "noun",
  traditionalMeaning: "madax-xanuun",
  modernMeaning: null,
  example: "She suffers from headache.",
  synonyms: [],
  isTech: false
},
{
  id: 128,
  word: "diabetes",
  language: "english",
  type: "noun",
  traditionalMeaning: "sonkorow",
  modernMeaning: null,
  example: "Diabetes requires careful monitoring.",
  synonyms: [],
  isTech: false
},
{
  id: 129,
  word: "hypertension",
  language: "english",
  type: "noun",
  traditionalMeaning: "dhiig-karka",
  modernMeaning: null,
  example: "Hypertension affects the heart.",
  synonyms: ["high blood pressure"],
  isTech: false
},
{
  id: 130,
  word: "fracture",
  language: "english",
  type: "noun",
  traditionalMeaning: "jab",
  modernMeaning: null,
  example: "The fracture needs treatment.",
  synonyms: ["broken bone"],
  isTech: false
},
{
  id: 131,
  word: "cancer",
  language: "english",
  type: "noun",
  traditionalMeaning: "kansar",
  modernMeaning: null,
  example: "Cancer treatment is improving.",
  synonyms: ["malignancy"],
  isTech: false
},
{
  id: 132,
  word: "virus",
  language: "english",
  type: "noun",
  traditionalMeaning: "fayras",
  modernMeaning: null,
  example: "The virus spreads fast.",
  synonyms: [],
  isTech: false
},
{
  id: 133,
  word: "bacteria",
  language: "english",
  type: "noun",
  traditionalMeaning: "bakteeriya",
  modernMeaning: null,
  example: "Bacteria can cause disease.",
  synonyms: [],
  isTech: false
},
{
  id: 134,
  word: "allergy",
  language: "english",
  type: "noun",
  traditionalMeaning: "xasaasiyad",
  modernMeaning: null,
  example: "He has a peanut allergy.",
  synonyms: [],
  isTech: false
},
{
  id: 135,
  word: "asthma",
  language: "english",
  type: "noun",
  traditionalMeaning: "neef",
  modernMeaning: null,
  example: "Asthma affects breathing.",
  synonyms: [],
  isTech: false
},
{
  id: 136,
  word: "anemia",
  language: "english",
  type: "noun",
  traditionalMeaning: "dhiig-yaraan",
  modernMeaning: null,
  example: "Anemia causes weakness.",
  synonyms: [],
  isTech: false
},
{
  id: 137,
  word: "pregnancy",
  language: "english",
  type: "noun",
  traditionalMeaning: "uur",
  modernMeaning: null,
  example: "Pregnancy requires care.",
  synonyms: [],
  isTech: false
},
{
  id: 138,
  word: "vaccine",
  language: "english",
  type: "noun",
  traditionalMeaning: "tallaal",
  modernMeaning: null,
  example: "The vaccine prevents disease.",
  synonyms: ["immunization"],
  isTech: false
},
{
  id: 139,
  word: "diagnosis",
  language: "english",
  type: "noun",
  traditionalMeaning: "ogaansho caafimaad",
  modernMeaning: null,
  example: "The diagnosis was accurate.",
  synonyms: [],
  isTech: false
},
{
  id: 140,
  word: "treatment",
  language: "english",
  type: "noun",
  traditionalMeaning: "daaweyn",
  modernMeaning: null,
  example: "Treatment started immediately.",
  synonyms: ["therapy"],
  isTech: false
},
{
  id: 141,
  word: "surgery",
  language: "english",
  type: "noun",
  traditionalMeaning: "qalliin",
  modernMeaning: null,
  example: "The surgery was successful.",
  synonyms: ["operation"],
  isTech: false
},
{
  id: 142,
  word: "emergency",
  language: "english",
  type: "noun",
  traditionalMeaning: "xaalad degdeg ah",
  modernMeaning: null,
  example: "This is a medical emergency.",
  synonyms: [],
  isTech: false
},
{
  id: 143,
  word: "ambulance",
  language: "english",
  type: "noun",
  traditionalMeaning: "gaari gurmad",
  modernMeaning: null,
  example: "Call the ambulance quickly.",
  synonyms: [],
  isTech: false
},
// ===== PROFESSIONAL MEDICAL PACK (Batch 2) =====

{
  id: 144,
  word: "cardiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga wadnaha",
  modernMeaning: null,
  example: "Cardiology focuses on heart diseases.",
  synonyms: [],
  isTech: false
},
{
  id: 145,
  word: "neurology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga neerfaha",
  modernMeaning: null,
  example: "Neurology studies the nervous system.",
  synonyms: [],
  isTech: false
},
{
  id: 146,
  word: "dermatology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga maqaarka",
  modernMeaning: null,
  example: "Dermatology treats skin conditions.",
  synonyms: [],
  isTech: false
},
{
  id: 147,
  word: "orthopedics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga lafaha",
  modernMeaning: null,
  example: "Orthopedics deals with bone injuries.",
  synonyms: [],
  isTech: false
},
{
  id: 148,
  word: "pediatrics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga carruurta",
  modernMeaning: null,
  example: "Pediatrics treats children.",
  synonyms: [],
  isTech: false
},
{
  id: 149,
  word: "gynecology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga haweenka",
  modernMeaning: null,
  example: "Gynecology focuses on women’s health.",
  synonyms: [],
  isTech: false
},
{
  id: 150,
  word: "psychiatry",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga maskaxda iyo dhimirka",
  modernMeaning: null,
  example: "Psychiatry treats mental disorders.",
  synonyms: [],
  isTech: false
},
{
  id: 151,
  word: "radiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga raajada",
  modernMeaning: null,
  example: "Radiology uses imaging technology.",
  synonyms: [],
  isTech: false
},
{
  id: 152,
  word: "anesthesia",
  language: "english",
  type: "noun",
  traditionalMeaning: "suuxdin caafimaad",
  modernMeaning: null,
  example: "Anesthesia prevents pain during surgery.",
  synonyms: [],
  isTech: false
},
{
  id: 153,
  word: "pathology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga cudurrada",
  modernMeaning: null,
  example: "Pathology studies disease causes.",
  synonyms: [],
  isTech: false
},
{
  id: 154,
  word: "epidemiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga faafidda cudurrada",
  modernMeaning: null,
  example: "Epidemiology tracks disease outbreaks.",
  synonyms: [],
  isTech: false
},
{
  id: 155,
  word: "oncology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kansarka",
  modernMeaning: null,
  example: "Oncology treats cancer patients.",
  synonyms: [],
  isTech: false
},
{
  id: 156,
  word: "immunology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga difaaca jirka",
  modernMeaning: null,
  example: "Immunology studies immune responses.",
  synonyms: [],
  isTech: false
},
{
  id: 157,
  word: "hematology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga dhiigga",
  modernMeaning: null,
  example: "Hematology examines blood disorders.",
  synonyms: [],
  isTech: false
},
{
  id: 158,
  word: "nephrology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kilyaha",
  modernMeaning: null,
  example: "Nephrology treats kidney diseases.",
  synonyms: [],
  isTech: false
},
{
  id: 159,
  word: "pulmonology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga sambabada",
  modernMeaning: null,
  example: "Pulmonology deals with lung disorders.",
  synonyms: [],
  isTech: false
},
{
  id: 160,
  word: "gastroenterology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga caloosha iyo mindhicirka",
  modernMeaning: null,
  example: "Gastroenterology treats digestive diseases.",
  synonyms: [],
  isTech: false
},
{
  id: 161,
  word: "urology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kaadi-mareenka",
  modernMeaning: null,
  example: "Urology focuses on urinary system.",
  synonyms: [],
  isTech: false
},
{
  id: 162,
  word: "obstetrics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga dhalmada",
  modernMeaning: null,
  example: "Obstetrics manages pregnancy and childbirth.",
  synonyms: [],
  isTech: false
},

{
  id: 163,
  word: "rehabilitation",
  language: "english",
  type: "noun",
  traditionalMeaning: "soo kabasho",
  modernMeaning: null,
  example: "Rehabilitation helps recovery.",
  synonyms: [],
  isTech: false
},
{
  id: 164,
  word: "Dropout",
  language: "english",
  type: "noun",
  traditionalMeaning: "Dhicis",
  modernMeaning: null,
  example: "The student became a dropout.",
  synonyms: [],
  isTech: false
},
{
  id: 165,
  word: "Dhicis",
  language: "somali",
  type: "noun",
  traditionalMeaning: "dropout",
  modernMeaning: null,
  example: "Ardeygi imtixaanki ayu dhacey, dhulka ayaan ku dhacey.",
  synonyms: [],
  isTech: false
},
{
  id: 166,
  word: "Aaamus",
  language: "somali",
  type: "noun",
  traditionalMeaning: "Silence",
  modernMeaning: null,
  example: "Waan aamusay markii aan maqlo wararka xun.",
  synonyms: [],
  isTech: false
},

];

const wordOfTheDay = dictionary[Math.floor(new Date().getDate() % dictionary.length)];