// ──────────────────────────────────────────────────────────
//  Higaad — Medical Words Data
//  medicalData.js — Bilingual Somali-English medical terms
// ──────────────────────────────────────────────────────────

const medicalDictionary = [
  {
    id: 1001,
    word: "heart",
    language: "english",
    type: "noun",
    somaliWord: "wadne",
    traditionalMeaning: "Wadnaha — the organ that pumps blood through the body",
    modernMeaning: "Wadne",
    example: "The heart beats about 100,000 times a day.",
    category: "anatomy",
    synonyms: ["cardiac muscle", "myocardium"],
    isMedical: true
  },
  {
    id: 1002,
    word: "wadne",
    language: "somali",
    type: "noun",
    somaliWord: "wadne",
    traditionalMeaning: "heart — the organ that pumps blood",
    modernMeaning: null,
    example: "Wadnahu waa gabar aad u muhiim ah.",
    category: "anatomy",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1003,
    word: "blood",
    language: "english",
    type: "noun",
    somaliWord: "dhiig",
    traditionalMeaning: "Dhiig — the red fluid that circulates through the body",
    modernMeaning: "Dhiig",
    example: "Blood carries oxygen to all organs.",
    category: "anatomy",
    synonyms: ["plasma", "hemoglobin"],
    isMedical: true
  },
  {
    id: 1004,
    word: "dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig",
    traditionalMeaning: "blood — red fluid circulating in the body",
    modernMeaning: null,
    example: "Dhiigu wuxuu qaadaa oksijiinta.",
    category: "anatomy",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1005,
    word: "doctor",
    language: "english",
    type: "noun",
    somaliWord: "dhakhtar",
    traditionalMeaning: "Dhakhtar — a licensed medical professional",
    modernMeaning: "Dhakhtar",
    example: "The doctor examined the patient carefully.",
    category: "profession",
    synonyms: ["physician", "medic", "clinician"],
    isMedical: true
  },
  {
    id: 1006,
    word: "dhakhtar",
    language: "somali",
    type: "noun",
    somaliWord: "dhakhtar",
    traditionalMeaning: "doctor — a licensed medical professional",
    modernMeaning: null,
    example: "Dhaktorku wuu baaray bukaan-socodyaasha.",
    category: "profession",
    synonyms: ["khabiir caafimaad"],
    isMedical: true
  },
  {
    id: 1007,
    word: "hospital",
    language: "english",
    type: "noun",
    somaliWord: "isbitaal",
    traditionalMeaning: "Isbitaal — a medical institution for treating the sick",
    modernMeaning: "Isbitaal",
    example: "She was admitted to the hospital.",
    category: "facility",
    synonyms: ["clinic", "medical center", "infirmary"],
    isMedical: true
  },
  {
    id: 1008,
    word: "isbitaal",
    language: "somali",
    type: "noun",
    somaliWord: "isbitaal",
    traditionalMeaning: "hospital — a building where sick people are treated",
    modernMeaning: null,
    example: "Isbitaalka cusub ayaa la furay.",
    category: "facility",
    synonyms: ["xarunta caafimaadka"],
    isMedical: true
  },
  {
    id: 1009,
    word: "fever",
    language: "english",
    type: "noun",
    somaliWord: "qandho",
    traditionalMeaning: "Qandho — abnormally high body temperature, usually a sign of infection",
    modernMeaning: "Qandho",
    example: "The child had a high fever overnight.",
    category: "symptom",
    synonyms: ["pyrexia", "high temperature"],
    isMedical: true
  },
  {
    id: 1010,
    word: "qandho",
    language: "somali",
    type: "noun",
    somaliWord: "qandho",
    traditionalMeaning: "fever — abnormally high body temperature",
    modernMeaning: null,
    example: "Ilmuhu wuxuu qabo qandho.",
    category: "symptom",
    synonyms: ["kulaylka jidhka"],
    isMedical: true
  },
  {
    id: 1011,
    word: "medicine",
    language: "english",
    type: "noun",
    somaliWord: "dawo",
    traditionalMeaning: "Dawo — a substance used to treat illness or injury",
    modernMeaning: "Dawo",
    example: "Take this medicine twice a day.",
    category: "treatment",
    synonyms: ["drug", "medication", "remedy"],
    isMedical: true
  },
  {
    id: 1012,
    word: "dawo",
    language: "somali",
    type: "noun",
    somaliWord: "dawo",
    traditionalMeaning: "medicine — a drug or remedy for illness",
    modernMeaning: null,
    example: "Dawada waxaad qaadataa laba jeer maalintii.",
    category: "treatment",
    synonyms: ["daawo", "ku-daweyn"],
    isMedical: true
  },
  {
    id: 1013,
    word: "bone",
    language: "english",
    type: "noun",
    somaliWord: "lafta",
    traditionalMeaning: "Lafta — rigid connective tissue forming the skeleton",
    modernMeaning: "Laf",
    example: "Calcium strengthens your bones.",
    category: "anatomy",
    synonyms: ["ossicle", "skeleton"],
    isMedical: true
  },
  {
    id: 1014,
    word: "lafta",
    language: "somali",
    type: "noun",
    somaliWord: "lafta",
    traditionalMeaning: "bone — hard structure forming the skeleton",
    modernMeaning: null,
    example: "Lafteydu way jab-jabantay.",
    category: "anatomy",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1015,
    word: "lung",
    language: "english",
    type: "noun",
    somaliWord: "sambab",
    traditionalMeaning: "Sambab — the organ responsible for breathing and gas exchange",
    modernMeaning: "Sambab",
    example: "Smoking damages your lungs.",
    category: "anatomy",
    synonyms: ["pulmonary organ"],
    isMedical: true
  },
  {
    id: 1016,
    word: "sambab",
    language: "somali",
    type: "noun",
    somaliWord: "sambab",
    traditionalMeaning: "lung — organ used for breathing",
    modernMeaning: null,
    example: "Sigaarka wuxuu waxyeeleyaa sambabyada.",
    category: "anatomy",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1017,
    word: "surgery",
    language: "english",
    type: "noun",
    somaliWord: "qalliin",
    traditionalMeaning: "Qalliin — a medical procedure involving incision into the body",
    modernMeaning: "Qalliin",
    example: "The surgery lasted three hours.",
    category: "treatment",
    synonyms: ["operation", "procedure"],
    isMedical: true
  },
  {
    id: 1018,
    word: "qalliin",
    language: "somali",
    type: "noun",
    somaliWord: "qalliin",
    traditionalMeaning: "surgery — a medical operation on the body",
    modernMeaning: null,
    example: "Qalliinka wuxuu qaatay saddex saacadood.",
    category: "treatment",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1019,
    word: "pregnancy",
    language: "english",
    type: "noun",
    somaliWord: "uur",
    traditionalMeaning: "Uur — the condition of carrying a developing fetus",
    modernMeaning: "Uur",
    example: "A healthy pregnancy lasts about 40 weeks.",
    category: "reproductive",
    synonyms: ["gestation", "expecting"],
    isMedical: true
  },
  {
    id: 1020,
    word: "uur",
    language: "somali",
    type: "noun",
    somaliWord: "uur",
    traditionalMeaning: "pregnancy — carrying a baby in the womb",
    modernMeaning: null,
    example: "Uurka caafimaadk wuxuu qaataa 40 wiig.",
    category: "reproductive",
    synonyms: ["ilmo-galeenimo"],
    isMedical: true
  },
  {
    id: 1021,
    word: "diabetes",
    language: "english",
    type: "noun",
    somaliWord: "sokor-xanuun",
    traditionalMeaning: "Sokor-xanuun — a chronic disease affecting blood sugar regulation",
    modernMeaning: "Sokor-xanuun",
    example: "Diabetes requires daily monitoring.",
    category: "disease",
    synonyms: ["hyperglycemia", "insulin resistance"],
    isMedical: true
  },
  {
    id: 1022,
    word: "sokor-xanuun",
    language: "somali",
    type: "noun",
    somaliWord: "sokor-xanuun",
    traditionalMeaning: "diabetes — a chronic illness affecting blood sugar",
    modernMeaning: null,
    example: "Sokor-xanuunka waxaa lagula dagaalamaa dawo iyo cunto fiican.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1023,
    word: "vaccination",
    language: "english",
    type: "noun",
    somaliWord: "tallaal",
    traditionalMeaning: "Tallaal — injection of a vaccine to stimulate immunity",
    modernMeaning: "Tallaal",
    example: "Vaccination prevents many deadly diseases.",
    category: "prevention",
    synonyms: ["immunization", "inoculation"],
    isMedical: true
  },
  {
    id: 1024,
    word: "tallaal",
    language: "somali",
    type: "noun",
    somaliWord: "tallaal",
    traditionalMeaning: "vaccination — an injection to protect against disease",
    modernMeaning: null,
    example: "Tallaalka cocowl waa muhiim carruurta.",
    category: "prevention",
    synonyms: ["ka-difaac xanuun"],
    isMedical: true
  },
  {
    id: 1025,
    word: "pain",
    language: "english",
    type: "noun",
    somaliWord: "xanuun",
    traditionalMeaning: "Xanuun — physical suffering or discomfort caused by illness or injury",
    modernMeaning: "Xanuun",
    example: "She felt pain in her lower back.",
    category: "symptom",
    synonyms: ["ache", "soreness", "discomfort"],
    isMedical: true
  },
  {
    id: 1026,
    word: "xanuun",
    language: "somali",
    type: "noun",
    somaliWord: "xanuun",
    traditionalMeaning: "pain — physical suffering or illness",
    modernMeaning: null,
    example: "Xanuunka dhabarka ayaan dareemay.",
    category: "symptom",
    synonyms: ["dhibaato", "murugayn"],
    isMedical: true
  },
  {
    id: 1027,
    word: "nurse",
    language: "english",
    type: "noun",
    somaliWord: "kalkaaliye",
    traditionalMeaning: "Kalkaaliye — a trained healthcare professional who cares for patients",
    modernMeaning: "Kalkaaliye",
    example: "The nurse checked the patient's vitals.",
    category: "profession",
    synonyms: ["caregiver", "health worker"],
    isMedical: true
  },
  {
    id: 1028,
    word: "kalkaaliye",
    language: "somali",
    type: "noun",
    somaliWord: "kalkaaliye",
    traditionalMeaning: "nurse — a trained medical caregiver",
    modernMeaning: null,
    example: "Kalkaaliyuhu wuxuu kaalin muhiim ah ka ciyaaraa isbitaalka.",
    category: "profession",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1029,
    word: "brain",
    language: "english",
    type: "noun",
    somaliWord: "maskax",
    traditionalMeaning: "Maskax — the organ inside the skull that controls all body functions",
    modernMeaning: "Maskax",
    example: "The brain contains about 86 billion neurons.",
    category: "anatomy",
    synonyms: ["cerebrum", "cranium", "mind"],
    isMedical: true
  },
  {
    id: 1030,
    word: "maskax",
    language: "somali",
    type: "noun",
    somaliWord: "maskax",
    traditionalMeaning: "brain — the organ controlling all body functions",
    modernMeaning: null,
    example: "Maskaxdu waxay xukumtaa jirka oo dhan.",
    category: "anatomy",
    synonyms: ["caqli"],
    isMedical: true
  },
  {
    id: 1031,
    word: "infection",
    language: "english",
    type: "noun",
    somaliWord: "cudur-qaadid",
    traditionalMeaning: "Cudur-qaadid — invasion of the body by harmful microorganisms",
    modernMeaning: "Cudur-qaadid",
    example: "The wound showed signs of infection.",
    category: "disease",
    synonyms: ["sepsis", "contamination"],
    isMedical: true
  },
  {
    id: 1032,
    word: "cudur",
    language: "somali",
    type: "noun",
    somaliWord: "cudur",
    traditionalMeaning: "disease / illness — a medical condition affecting the body",
    modernMeaning: null,
    example: "Cudurku waa mid fara badan.",
    category: "disease",
    synonyms: ["xanuun", "bukaan"],
    isMedical: true
  },
  {
    id: 1033,
    word: "ambulance",
    language: "english",
    type: "noun",
    somaliWord: "baabuur-caafimaad",
    traditionalMeaning: "Baabuur-caafimaad — an emergency vehicle for transporting patients",
    modernMeaning: "Baabuur-caafimaad",
    example: "Call an ambulance immediately!",
    category: "facility",
    synonyms: ["emergency vehicle"],
    isMedical: true
  },
  {
    id: 1034,
    word: "baabuur-caafimaad",
    language: "somali",
    type: "noun",
    somaliWord: "baabuur-caafimaad",
    traditionalMeaning: "ambulance — emergency vehicle for patients",
    modernMeaning: null,
    example: "Wac baabuurka caafimaadka hadda!",
    category: "facility",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1035,
    word: "allergy",
    language: "english",
    type: "noun",
    somaliWord: "xasaasi",
    traditionalMeaning: "Xasaasi — an immune reaction to substances that are normally harmless",
    modernMeaning: "Xasaasi",
    example: "She has a severe allergy to peanuts.",
    category: "disease",
    synonyms: ["hypersensitivity", "reaction"],
    isMedical: true
  },
  {
    id: 1036,
    word: "xasaasi",
    language: "somali",
    type: "noun",
    somaliWord: "xasaasi",
    traditionalMeaning: "allergy — immune reaction to harmless substances",
    modernMeaning: null,
    example: "Xasaasiyadeydu waxay ka timid midabka abuurka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1037,
    word: "malaria",
    language: "english",
    type: "noun",
    somaliWord: "duumada / gowracid",
    traditionalMeaning: "Malaaria — a mosquito-borne infectious disease causing fever",
    modernMeaning: "Malaaria",
    example: "Malaria is preventable with mosquito nets.",
    category: "disease",
    synonyms: ["plasmodium infection"],
    isMedical: true
  },
  {
    id: 1038,
    word: "vitamin",
    language: "english",
    type: "noun",
    somaliWord: "fiitamiin",
    traditionalMeaning: "Fiitamiin — essential organic compound needed for normal body function",
    modernMeaning: "Fiitamiin",
    example: "Vitamin C boosts the immune system.",
    category: "nutrition",
    synonyms: ["nutrient", "supplement"],
    isMedical: true
  },
  {
    id: 1039,
    word: "fiitamiin",
    language: "somali",
    type: "noun",
    somaliWord: "fiitamiin",
    traditionalMeaning: "vitamin — essential nutrient for body functions",
    modernMeaning: null,
    example: "Fiitamiin C waxay xoojisaa difaaca jirka.",
    category: "nutrition",
    synonyms: [],
    isMedical: true
  },
  {
    id: 1040,
    word: "kidney",
    language: "english",
    type: "noun",
    somaliWord: "kaadi-gal",
    traditionalMeaning: "Kaadi-gal — the organ that filters blood and produces urine",
    modernMeaning: "Kaadi-gal",
    example: "Drinking water protects your kidneys.",
    category: "anatomy",
    synonyms: ["renal organ"],
    isMedical: true
  },
  {
    id: 1041,
    word: "kaadi-gal",
    language: "somali",
    type: "noun",
    somaliWord: "kaadi-gal",
    traditionalMeaning: "kidney — organ that filters blood and makes urine",
    modernMeaning: null,
    example: "Kaadi-galku wuu xanuunsaday.",
    category: "anatomy",
    synonyms: ["kiidni"],
    isMedical: true
  },
  {
    id: 1042,
    word: "health",
    language: "english",
    type: "noun",
    somaliWord: "caafimaad",
    traditionalMeaning: "Caafimaad — the state of being free from illness or injury",
    modernMeaning: "Caafimaad",
    example: "Good health is the greatest wealth.",
    category: "general",
    synonyms: ["wellness", "wellbeing"],
    isMedical: true
  },
  {
    id: 1043,
    word: "caafimaad",
    language: "somali",
    type: "noun",
    somaliWord: "caafimaad",
    traditionalMeaning: "health — the state of being well",
    modernMeaning: null,
    example: "Caafimaadku waa mid aad u qaaliga ah.",
    category: "general",
    synonyms: ["fayow", "nadaafad"],
    isMedical: true
  },
  {
    id: 1044,
    word: "blood pressure",
    language: "english",
    type: "noun",
    somaliWord: "cadaadiska dhiigga",
    traditionalMeaning: "Cadaadiska dhiigga — the pressure of circulating blood on vessel walls",
    modernMeaning: "Cadaadis-dhiig",
    example: "High blood pressure is called hypertension.",
    category: "vital signs",
    synonyms: ["hypertension", "BP"],
    isMedical: true
  },
  {
    id: 1045,
    word: "cadaadis-dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "cadaadis-dhiig",
    traditionalMeaning: "blood pressure — pressure of blood in the vessels",
    modernMeaning: null,
    example: "Cadaadiska dhiiggiisu waa sare.",
    category: "vital signs",
    synonyms: [],
    isMedical: true
  },
  // ===== PROFESSIONAL MEDICAL PACK (Batch 2) =====

{
  id: 144,
  word: "cardiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga wadnaha",
  modernMeaning: null,
  example: "Cardiology focuses on heart diseases.",
  synonyms: [],
  isTech: false
},
{
  id: 145,
  word: "neurology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga neerfaha",
  modernMeaning: null,
  example: "Neurology studies the nervous system.",
  synonyms: [],
  isTech: false
},
{
  id: 146,
  word: "dermatology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga maqaarka",
  modernMeaning: null,
  example: "Dermatology treats skin conditions.",
  synonyms: [],
  isTech: false
},
{
  id: 147,
  word: "orthopedics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga lafaha",
  modernMeaning: null,
  example: "Orthopedics deals with bone injuries.",
  synonyms: [],
  isTech: false
},
{
  id: 148,
  word: "pediatrics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga carruurta",
  modernMeaning: null,
  example: "Pediatrics treats children.",
  synonyms: [],
  isTech: false
},
{
  id: 149,
  word: "gynecology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga haweenka",
  modernMeaning: null,
  example: "Gynecology focuses on women’s health.",
  synonyms: [],
  isTech: false
},
{
  id: 150,
  word: "psychiatry",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga maskaxda iyo dhimirka",
  modernMeaning: null,
  example: "Psychiatry treats mental disorders.",
  synonyms: [],
  isTech: false
},
{
  id: 151,
  word: "radiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga raajada",
  modernMeaning: null,
  example: "Radiology uses imaging technology.",
  synonyms: [],
  isTech: false
},
{
  id: 152,
  word: "anesthesia",
  language: "english",
  type: "noun",
  traditionalMeaning: "suuxdin caafimaad",
  modernMeaning: null,
  example: "Anesthesia prevents pain during surgery.",
  synonyms: [],
  isTech: false
},
{
  id: 153,
  word: "pathology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga cudurrada",
  modernMeaning: null,
  example: "Pathology studies disease causes.",
  synonyms: [],
  isTech: false
},
{
  id: 154,
  word: "epidemiology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga faafidda cudurrada",
  modernMeaning: null,
  example: "Epidemiology tracks disease outbreaks.",
  synonyms: [],
  isTech: false
},
{
  id: 155,
  word: "oncology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kansarka",
  modernMeaning: null,
  example: "Oncology treats cancer patients.",
  synonyms: [],
  isTech: false
},
{
  id: 156,
  word: "immunology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga difaaca jirka",
  modernMeaning: null,
  example: "Immunology studies immune responses.",
  synonyms: [],
  isTech: false
},
{
  id: 157,
  word: "hematology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga dhiigga",
  modernMeaning: null,
  example: "Hematology examines blood disorders.",
  synonyms: [],
  isTech: false
},
{
  id: 158,
  word: "nephrology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kilyaha",
  modernMeaning: null,
  example: "Nephrology treats kidney diseases.",
  synonyms: [],
  isTech: false
},
{
  id: 159,
  word: "pulmonology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga sambabada",
  modernMeaning: null,
  example: "Pulmonology deals with lung disorders.",
  synonyms: [],
  isTech: false
},
{
  id: 160,
  word: "gastroenterology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga caloosha iyo mindhicirka",
  modernMeaning: null,
  example: "Gastroenterology treats digestive diseases.",
  synonyms: [],
  isTech: false
},
{
  id: 161,
  word: "urology",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga kaadi-mareenka",
  modernMeaning: null,
  example: "Urology focuses on urinary system.",
  synonyms: [],
  isTech: false
},
{
  id: 162,
  word: "obstetrics",
  language: "english",
  type: "noun",
  traditionalMeaning: "cilmiga dhalmada",
  modernMeaning: null,
  example: "Obstetrics manages pregnancy and childbirth.",
  synonyms: [],
  isTech: false
},
{
  id: 163,
  word: "rehabilitation",
  language: "english",
  type: "noun",
  traditionalMeaning: "soo kabasho",
  modernMeaning: null,
  example: "Rehabilitation helps recovery.",
  synonyms: [],
  isTech: false
},
{
  id: 164,
  word: "Dr.abdifitah jama",
  language: "english",
  type: "Person",
  traditionalMeaning: "Dr.abdifitah jama — a medical professional known for expertise in healthcare and patient care in Somaliland.",
  modernMeaning: null,
  example: "Dr.abdifitah jama is a medical professional.",
  synonyms: [],
  isTech: false
},
{
  id: 165,
  word: "Dr. Mohamed Abdi Hergeye",
  language: "english",
  type: "Person",
  traditionalMeaning: "dr. Mohamed Abdi Hergeye — a medical professional recognized for contributions to healthcare and medical education in Somaliland.",
  modernMeaning: null,
  example: "dr. Mohamed Abdi Hergeye is a medical professional.",
  synonyms: [],
  isTech: false
},
{
  id: 166,
  word: "Dr. Fathia Mohamed Nour",
  language: "english",
  type: "Person",
  traditionalMeaning: "Family Medicine specialist based in Borama (Amoud University College of Health Sciences). Dr. Fathia is known for her dedication to improving healthcare access and quality in Somaliland, particularly in rural areas.",
  modernMeaning: null,
  example: "dr. Fathia Mohamed Nour is a medical professional.",
  synonyms: [],
  isTech: false
},

  {
    id: 1062,
    word: "ulcer",
    language: "english",
    type: "noun",
    somaliWord: "boog-calooleed",
    traditionalMeaning: "Boog-calooleed — a sore that develops on the lining of the stomach or intestine",
    modernMeaning: "Boog-calooleed",
    example: "Stress can worsen a stomach ulcer.",
    category: "disease",
    synonyms: ["peptic ulcer"],
    isMedical: true
  },
  {
    id: 1063,
    word: "boog-calooleed",
    language: "somali",
    type: "noun",
    somaliWord: "boog-calooleed",
    traditionalMeaning: "ulcer — nabar ku dhaca caloosha",
    modernMeaning: null,
    example: "Boog-calooleedku wuxuu keenaa xanuun daran.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1064,
    word: "arthritis",
    language: "english",
    type: "noun",
    somaliWord: "barar-kala-goys",
    traditionalMeaning: "Barar-kala-goys — inflammation of one or more joints",
    modernMeaning: "Barar-kala-goys",
    example: "Arthritis causes joint stiffness.",
    category: "disease",
    synonyms: ["joint inflammation"],
    isMedical: true
  },
  {
    id: 1065,
    word: "barar-kala-goys",
    language: "somali",
    type: "noun",
    somaliWord: "barar-kala-goys",
    traditionalMeaning: "arthritis — barar ku dhaca kala-goysyada",
    modernMeaning: null,
    example: "Barar-kala-goysku wuxuu adkeeyaa dhaqaaqa.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1066,
    word: "migraine",
    language: "english",
    type: "noun",
    somaliWord: "madax-xanuun-daran",
    traditionalMeaning: "Madax-xanuun-daran — a severe recurring headache",
    modernMeaning: "Madax-xanuun-daran",
    example: "Migraine may cause sensitivity to light.",
    category: "disease",
    synonyms: ["vascular headache"],
    isMedical: true
  },
  {
    id: 1067,
    word: "madax-xanuun-daran",
    language: "somali",
    type: "noun",
    somaliWord: "madax-xanuun-daran",
    traditionalMeaning: "migraine — madax xanuun soo noqnoqda",
    modernMeaning: null,
    example: "Madax-xanuun-daran ayaa iga haya subax walba.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1068,
    word: "insomnia",
    language: "english",
    type: "noun",
    somaliWord: "hurdo-la'aan",
    traditionalMeaning: "Hurdo-la'aan — difficulty in falling or staying asleep",
    modernMeaning: "Hurdo-la'aan",
    example: "Insomnia affects mental health.",
    category: "condition",
    synonyms: ["sleep disorder"],
    isMedical: true
  },
  {
    id: 1069,
    word: "hurdo-la'aan",
    language: "somali",
    type: "noun",
    somaliWord: "hurdo-la'aan",
    traditionalMeaning: "insomnia — hurdada oo ku yaraata",
    modernMeaning: null,
    example: "Hurdo-la'aantu waxay keentaa daal.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1070,
    word: "obesity",
    language: "english",
    type: "noun",
    somaliWord: "buurni-xad-dhaaf",
    traditionalMeaning: "Buurni-xad-dhaaf — excessive body fat accumulation",
    modernMeaning: "Buurni-xad-dhaaf",
    example: "Obesity increases diabetes risk.",
    category: "condition",
    synonyms: ["overweight"],
    isMedical: true
  },
  {
    id: 1071,
    word: "buurni-xad-dhaaf",
    language: "somali",
    type: "noun",
    somaliWord: "buurni-xad-dhaaf",
    traditionalMeaning: "obesity — miisaan aad u badan",
    modernMeaning: null,
    example: "Buurni-xad-dhaafku waa dhibaato caafimaad.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1072,
    word: "pneumonia",
    language: "english",
    type: "noun",
    somaliWord: "oof-wareen",
    traditionalMeaning: "Oof-wareen — lung infection causing inflammation",
    modernMeaning: "Oof-wareen",
    example: "Pneumonia can be life-threatening.",
    category: "disease",
    synonyms: ["lung infection"],
    isMedical: true
  },
  {
    id: 1073,
    word: "oof-wareen",
    language: "somali",
    type: "noun",
    somaliWord: "oof-wareen",
    traditionalMeaning: "pneumonia — caabuq ku dhaca sambabada",
    modernMeaning: null,
    example: "Oof-wareenku wuxuu saameeyaa neefsashada.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1074,
    word: "hemorrhoids",
    language: "english",
    type: "noun",
    somaliWord: "baabasiir",
    traditionalMeaning: "Baabasiir — swollen veins in the lower rectum",
    modernMeaning: "Baabasiir",
    example: "Hemorrhoids cause rectal pain.",
    category: "disease",
    synonyms: ["piles"],
    isMedical: true
  },
  {
    id: 1075,
    word: "baabasiir",
    language: "somali",
    type: "noun",
    somaliWord: "baabasiir",
    traditionalMeaning: "hemorrhoids — xidid barara malawadka",
    modernMeaning: null,
    example: "Baabasiirku wuxuu keenaa xanuun iyo dhiig.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1076,
    word: "jaundice",
    language: "english",
    type: "noun",
    somaliWord: "cagaarshow",
    traditionalMeaning: "Cagaarshow — yellowing of the skin due to liver problems",
    modernMeaning: "Cagaarshow",
    example: "Jaundice is common in newborns.",
    category: "disease",
    synonyms: ["bilirubin disorder"],
    isMedical: true
  },
  {
    id: 1077,
    word: "cagaarshow",
    language: "somali",
    type: "noun",
    somaliWord: "cagaarshow",
    traditionalMeaning: "jaundice — maqaarka oo huruud noqda",
    modernMeaning: null,
    example: "Cagaarshowgu wuxuu ka yimaadaa beer-xanuun.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1078,
    word: "appendicitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuqa-lifaaq",
    traditionalMeaning: "Caabuqa-lifaaq — inflammation of the appendix",
    modernMeaning: "Caabuqa-lifaaq",
    example: "Appendicitis requires urgent surgery.",
    category: "disease",
    synonyms: ["appendix inflammation"],
    isMedical: true
  },
  {
    id: 1079,
    word: "caabuqa-lifaaq",
    language: "somali",
    type: "noun",
    somaliWord: "caabuqa-lifaaq",
    traditionalMeaning: "appendicitis — barar ku dhaca lifaaqa mindhicirka",
    modernMeaning: null,
    example: "Caabuqa-lifaaq waa xaalad degdeg ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1080,
    word: "cirrhosis",
    language: "english",
    type: "noun",
    somaliWord: "beer-adkaansho",
    traditionalMeaning: "Beer-adkaansho — chronic liver damage leading to scarring",
    modernMeaning: "Beer-adkaansho",
    example: "Cirrhosis can result from long-term alcohol use.",
    category: "disease",
    synonyms: ["liver fibrosis"],
    isMedical: true
  },
  {
    id: 1081,
    word: "beer-adkaansho",
    language: "somali",
    type: "noun",
    somaliWord: "beer-adkaansho",
    traditionalMeaning: "cirrhosis — beerka oo nabro yeesha",
    modernMeaning: null,
    example: "Beer-adkaanshadu waxay saameysaa shaqada beerka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1082,
    word: "epilepsy",
    language: "english",
    type: "noun",
    somaliWord: "suuxdin-joogto",
    traditionalMeaning: "Suuxdin-joogto — neurological disorder causing recurrent seizures",
    modernMeaning: "Suuxdin-joogto",
    example: "Epilepsy can be managed with medication.",
    category: "disease",
    synonyms: ["seizure disorder"],
    isMedical: true
  },
  {
    id: 1083,
    word: "suuxdin-joogto",
    language: "somali",
    type: "noun",
    somaliWord: "suuxdin-joogto",
    traditionalMeaning: "epilepsy — suuxdin soo noqnoqda",
    modernMeaning: null,
    example: "Suuxdin-joogto waxay u baahan tahay daawo joogto ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1084,
    word: "ultrasound",
    language: "english",
    type: "noun",
    somaliWord: "sawir-dhawaaq",
    traditionalMeaning: "Sawir-dhawaaq — imaging technique using sound waves",
    modernMeaning: "Sawir-dhawaaq",
    example: "Ultrasound is commonly used during pregnancy.",
    category: "diagnostic",
    synonyms: ["sonography"],
    isMedical: true
  },
  {
    id: 1085,
    word: "sawir-dhawaaq",
    language: "somali",
    type: "noun",
    somaliWord: "sawir-dhawaaq",
    traditionalMeaning: "ultrasound — sawir lagu qaado hirar dhawaaq",
    modernMeaning: null,
    example: "Sawir-dhawaaq ayaa lagu eegay uurka.",
    category: "diagnostic",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1086,
    word: "dialysis",
    language: "english",
    type: "noun",
    somaliWord: "nadiifin-dhiig",
    traditionalMeaning: "Nadiifin-dhiig — artificial removal of waste from the blood",
    modernMeaning: "Nadiifin-dhiig",
    example: "Dialysis is needed in kidney failure.",
    category: "treatment",
    synonyms: ["renal replacement therapy"],
    isMedical: true
  },
  {
    id: 1087,
    word: "nadiifin-dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "nadiifin-dhiig",
    traditionalMeaning: "dialysis — dhiig si farsamo ah loo sifeeyo",
    modernMeaning: null,
    example: "Nadiifin-dhiig ayaa lagu sameeyaa bukaanka kelyo-fashilka.",
    category: "treatment",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1088,
    word: "anxiety",
    language: "english",
    type: "noun",
    somaliWord: "walbahaar",
    traditionalMeaning: "Walbahaar — feeling of worry or nervousness",
    modernMeaning: "Walbahaar",
    example: "Anxiety can affect daily life.",
    category: "mental health",
    synonyms: ["nervousness", "stress"],
    isMedical: true
  },
  {
    id: 1089,
    word: "walbahaar",
    language: "somali",
    type: "noun",
    somaliWord: "walbahaar",
    traditionalMeaning: "anxiety — dareen welwel iyo cabsi leh",
    modernMeaning: null,
    example: "Walbahaar badan ayaa saameeya hurdada.",
    category: "mental health",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1090,
    word: "glaucoma",
    language: "english",
    type: "noun",
    somaliWord: "cadaadis-indho",
    traditionalMeaning: "Cadaadis-indho — a condition causing increased pressure inside the eye leading to vision loss",
    modernMeaning: "Cadaadis-indho",
    example: "Glaucoma can cause permanent blindness if untreated.",
    category: "disease",
    synonyms: ["optic neuropathy"],
    isMedical: true
  },
  {
    id: 1091,
    word: "cadaadis-indho",
    language: "somali",
    type: "noun",
    somaliWord: "cadaadis-indho",
    traditionalMeaning: "glaucoma — cadaadis sare oo ku dhaca isha",
    modernMeaning: null,
    example: "Cadaadis-indho wuxuu dhaawici karaa neerfaha aragga.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1092,
    word: "hepatitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-beer",
    traditionalMeaning: "Caabuq-beer — inflammation of the liver usually caused by infection",
    modernMeaning: "Caabuq-beer",
    example: "Hepatitis can spread through contaminated blood.",
    category: "disease",
    synonyms: ["liver inflammation"],
    isMedical: true
  },
  {
    id: 1093,
    word: "caabuq-beer",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-beer",
    traditionalMeaning: "hepatitis — barar ku dhaca beerka",
    modernMeaning: null,
    example: "Caabuq-beerku wuxuu saameeyaa shaqada beerka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1094,
    word: "eczema",
    language: "english",
    type: "noun",
    somaliWord: "finan-maqaareed",
    traditionalMeaning: "Finan-maqaareed — inflammatory skin condition causing itching and redness",
    modernMeaning: "Finan-maqaareed",
    example: "Eczema often appears in childhood.",
    category: "disease",
    synonyms: ["dermatitis"],
    isMedical: true
  },
  {
    id: 1095,
    word: "finan-maqaareed",
    language: "somali",
    type: "noun",
    somaliWord: "finan-maqaareed",
    traditionalMeaning: "eczema — finan iyo cuncun ku dhaca maqaarka",
    modernMeaning: null,
    example: "Finan-maqaareedku wuxuu keenaa cuncun daran.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1096,
    word: "anaphylaxis",
    language: "english",
    type: "noun",
    somaliWord: "xasaasiyad-daran",
    traditionalMeaning: "Xasaasiyad-daran — severe allergic reaction that can be life-threatening",
    modernMeaning: "Xasaasiyad-daran",
    example: "Anaphylaxis requires immediate medical treatment.",
    category: "emergency",
    synonyms: ["severe allergic reaction"],
    isMedical: true
  },
  {
    id: 1097,
    word: "xasaasiyad-daran",
    language: "somali",
    type: "noun",
    somaliWord: "xasaasiyad-daran",
    traditionalMeaning: "anaphylaxis — falcelin xasaasiyadeed oo halis ah",
    modernMeaning: null,
    example: "Xasaasiyad-daran waa xaalad degdeg ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1098,
    word: "osteoporosis",
    language: "english",
    type: "noun",
    somaliWord: "laf-jileec",
    traditionalMeaning: "Laf-jileec — condition where bones become weak and fragile",
    modernMeaning: "Laf-jileec",
    example: "Osteoporosis increases fracture risk.",
    category: "disease",
    synonyms: ["bone density loss"],
    isMedical: true
  },
  {
    id: 1099,
    word: "laf-jileec",
    language: "somali",
    type: "noun",
    somaliWord: "laf-jileec",
    traditionalMeaning: "osteoporosis — lafo jilcaan oo fudud u jabta",
    modernMeaning: null,
    example: "Laf-jileec wuxuu ku badan yahay waayeelka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1100,
    word: "hypothyroidism",
    language: "english",
    type: "noun",
    somaliWord: "qanjir-yaraansho",
    traditionalMeaning: "Qanjir-yaraansho — underactive thyroid gland producing low hormones",
    modernMeaning: "Qanjir-yaraansho",
    example: "Hypothyroidism can cause weight gain.",
    category: "disease",
    synonyms: ["underactive thyroid"],
    isMedical: true
  },
  {
    id: 1101,
    word: "qanjir-yaraansho",
    language: "somali",
    type: "noun",
    somaliWord: "qanjir-yaraansho",
    traditionalMeaning: "hypothyroidism — qanjirka qoorta oo hormoon yar soo saara",
    modernMeaning: null,
    example: "Qanjir-yaraansho wuxuu sababi karaa daal.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1102,
    word: "pancreatitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-beeryar",
    traditionalMeaning: "Caabuq-beeryar — inflammation of the pancreas",
    modernMeaning: "Caabuq-beeryar",
    example: "Pancreatitis can cause severe abdominal pain.",
    category: "disease",
    synonyms: ["pancreatic inflammation"],
    isMedical: true
  },
  {
    id: 1103,
    word: "caabuq-beeryar",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-beeryar",
    traditionalMeaning: "pancreatitis — barar ku dhaca beeryarada",
    modernMeaning: null,
    example: "Caabuq-beeryar wuxuu keenaa xanuun caloosha ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1104,
    word: "bronchitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-neefmareen",
    traditionalMeaning: "Caabuq-neefmareen — inflammation of the bronchial tubes",
    modernMeaning: "Caabuq-neefmareen",
    example: "Bronchitis causes persistent coughing.",
    category: "disease",
    synonyms: ["bronchial inflammation"],
    isMedical: true
  },
  {
    id: 1105,
    word: "caabuq-neefmareen",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-neefmareen",
    traditionalMeaning: "bronchitis — barar ku dhaca marinnada neefsiga",
    modernMeaning: null,
    example: "Caabuq-neefmareenku wuxuu keenaa qufac joogto ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1106,
    word: "dermatitis",
    language: "english",
    type: "noun",
    somaliWord: "barar-maqaarka",
    traditionalMeaning: "Barar-maqaarka — inflammation of the skin",
    modernMeaning: "Barar-maqaarka",
    example: "Dermatitis can be triggered by allergies.",
    category: "disease",
    synonyms: ["skin inflammation"],
    isMedical: true
  },
  {
    id: 1107,
    word: "barar-maqaarka",
    language: "somali",
    type: "noun",
    somaliWord: "barar-maqaarka",
    traditionalMeaning: "dermatitis — barar ku dhaca maqaarka",
    modernMeaning: null,
    example: "Barar-maqaarka wuxuu sababi karaa cuncun.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1108,
    word: "arrhythmia",
    language: "english",
    type: "noun",
    somaliWord: "garaac-wadne-aan-caadi",
    traditionalMeaning: "Garaac-wadne-aan-caadi — irregular heartbeat",
    modernMeaning: "Garaac-wadne-aan-caadi",
    example: "Arrhythmia may require medical monitoring.",
    category: "disease",
    synonyms: ["irregular heartbeat"],
    isMedical: true
  },
  {
    id: 1109,
    word: "garaac-wadne-aan-caadi",
    language: "somali",
    type: "noun",
    somaliWord: "garaac-wadne-aan-caadi",
    traditionalMeaning: "arrhythmia — garaaca wadnaha oo khaldan",
    modernMeaning: null,
    example: "Garaac-wadne-aan-caadi wuxuu keeni karaa wareer.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1110,
    word: "sepsis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-dhiig",
    traditionalMeaning: "Caabuq-dhiig — life-threatening response to infection spreading in the bloodstream",
    modernMeaning: "Caabuq-dhiig",
    example: "Sepsis is a medical emergency.",
    category: "emergency",
    synonyms: ["blood infection"],
    isMedical: true
  },
  {
    id: 1111,
    word: "caabuq-dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-dhiig",
    traditionalMeaning: "sepsis — jeermis ku faafo dhiigga",
    modernMeaning: null,
    example: "Caabuq-dhiig waa xaalad halis ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1112,
    word: "hernia",
    language: "english",
    type: "noun",
    somaliWord: "xiidho-bax",
    traditionalMeaning: "Xiidho-bax — protrusion of an organ through surrounding muscle wall",
    modernMeaning: "Xiidho-bax",
    example: "Hernia may require surgical repair.",
    category: "disease",
    synonyms: ["protrusion"],
    isMedical: true
  },
  {
    id: 1113,
    word: "xiidho-bax",
    language: "somali",
    type: "noun",
    somaliWord: "xiidho-bax",
    traditionalMeaning: "hernia — xubinta caloosha oo ka soo baxda murqaha",
    modernMeaning: null,
    example: "Xiidho-bax waxaa lagu daaweeyaa qalliin.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1114,
    word: "gastritis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-calooleed",
    traditionalMeaning: "Caabuq-calooleed — inflammation of the stomach lining",
    modernMeaning: "Caabuq-calooleed",
    example: "Gastritis can cause burning stomach pain.",
    category: "disease",
    synonyms: ["stomach inflammation"],
    isMedical: true
  },
  {
    id: 1115,
    word: "caabuq-calooleed",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-calooleed",
    traditionalMeaning: "gastritis — barar ku dhaca xuubka caloosha",
    modernMeaning: null,
    example: "Caabuq-calooleedku wuxuu sababi karaa lalabo.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1116,
    word: "concussion",
    language: "english",
    type: "noun",
    somaliWord: "jug-maskaxeed",
    traditionalMeaning: "Jug-maskaxeed — mild traumatic brain injury caused by a blow to the head",
    modernMeaning: "Jug-maskaxeed",
    example: "The athlete suffered a concussion.",
    category: "injury",
    synonyms: ["brain trauma"],
    isMedical: true
  },
  {
    id: 1117,
    word: "jug-maskaxeed",
    language: "somali",
    type: "noun",
    somaliWord: "jug-maskaxeed",
    traditionalMeaning: "concussion — jug ku dhacda maskaxda",
    modernMeaning: null,
    example: "Jug-maskaxeed wuxuu keeni karaa wareer.",
    category: "injury",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1118,
    word: "cyst",
    language: "english",
    type: "noun",
    somaliWord: "kiish-biyood",
    traditionalMeaning: "Kiish-biyood — closed sac filled with fluid or semi-solid material",
    modernMeaning: "Kiish-biyood",
    example: "The cyst was removed surgically.",
    category: "disease",
    synonyms: ["fluid sac"],
    isMedical: true
  },
  {
    id: 1119,
    word: "kiish-biyood",
    language: "somali",
    type: "noun",
    somaliWord: "kiish-biyood",
    traditionalMeaning: "cyst — kiish yar oo dareere ku jira",
    modernMeaning: null,
    example: "Kiish-biyood ayaa laga helay maqaarka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1120,
    word: "hypertension crisis",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-kar-daran",
    traditionalMeaning: "Dhiig-kar-daran — severe elevation of blood pressure requiring urgent care",
    modernMeaning: "Dhiig-kar-daran",
    example: "Hypertension crisis can damage organs.",
    category: "emergency",
    synonyms: ["hypertensive emergency"],
    isMedical: true
  },
  {
    id: 1121,
    word: "dhiig-kar-daran",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-kar-daran",
    traditionalMeaning: "hypertension crisis — cadaadis dhiig oo aad u sareeya",
    modernMeaning: null,
    example: "Dhiig-kar-daran waa xaalad degdeg ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1122,
    word: "anemia severe",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-yaraan-daran",
    traditionalMeaning: "Dhiig-yaraan-daran — critically low red blood cell levels",
    modernMeaning: "Dhiig-yaraan-daran",
    example: "Severe anemia may require blood transfusion.",
    category: "disease",
    synonyms: ["critical anemia"],
    isMedical: true
  },
  {
    id: 1123,
    word: "dhiig-yaraan-daran",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-yaraan-daran",
    traditionalMeaning: "severe anemia — dhiig aad u yaraada",
    modernMeaning: null,
    example: "Dhiig-yaraan-daran waxay sababi kartaa suuxdin.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1124,
    word: "vertigo",
    language: "english",
    type: "noun",
    somaliWord: "wareer-wareeg",
    traditionalMeaning: "Wareer-wareeg — sensation of spinning dizziness",
    modernMeaning: "Wareer-wareeg",
    example: "Vertigo makes the room feel like it is spinning.",
    category: "symptom",
    synonyms: ["spinning dizziness"],
    isMedical: true
  },
  {
    id: 1125,
    word: "wareer-wareeg",
    language: "somali",
    type: "noun",
    somaliWord: "wareer-wareeg",
    traditionalMeaning: "vertigo — wareer qofku dareemo isagoo wareegaya",
    modernMeaning: null,
    example: "Wareer-wareeg ayaa iga haya marka aan istaago.",
    category: "symptom",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1114,
    word: "gastritis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-calooleed",
    traditionalMeaning: "Caabuq-calooleed — inflammation of the stomach lining",
    modernMeaning: "Caabuq-calooleed",
    example: "Gastritis can cause burning stomach pain.",
    category: "disease",
    synonyms: ["stomach inflammation"],
    isMedical: true
  },
  {
    id: 1115,
    word: "caabuq-calooleed",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-calooleed",
    traditionalMeaning: "gastritis — barar ku dhaca xuubka caloosha",
    modernMeaning: null,
    example: "Caabuq-calooleedku wuxuu sababi karaa lalabo.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1116,
    word: "concussion",
    language: "english",
    type: "noun",
    somaliWord: "jug-maskaxeed",
    traditionalMeaning: "Jug-maskaxeed — mild traumatic brain injury caused by a blow to the head",
    modernMeaning: "Jug-maskaxeed",
    example: "The athlete suffered a concussion.",
    category: "injury",
    synonyms: ["brain trauma"],
    isMedical: true
  },
  {
    id: 1117,
    word: "jug-maskaxeed",
    language: "somali",
    type: "noun",
    somaliWord: "jug-maskaxeed",
    traditionalMeaning: "concussion — jug ku dhacda maskaxda",
    modernMeaning: null,
    example: "Jug-maskaxeed wuxuu keeni karaa wareer.",
    category: "injury",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1118,
    word: "cyst",
    language: "english",
    type: "noun",
    somaliWord: "kiish-biyood",
    traditionalMeaning: "Kiish-biyood — closed sac filled with fluid or semi-solid material",
    modernMeaning: "Kiish-biyood",
    example: "The cyst was removed surgically.",
    category: "disease",
    synonyms: ["fluid sac"],
    isMedical: true
  },
  {
    id: 1119,
    word: "kiish-biyood",
    language: "somali",
    type: "noun",
    somaliWord: "kiish-biyood",
    traditionalMeaning: "cyst — kiish yar oo dareere ku jira",
    modernMeaning: null,
    example: "Kiish-biyood ayaa laga helay maqaarka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1120,
    word: "hypertension crisis",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-kar-daran",
    traditionalMeaning: "Dhiig-kar-daran — severe elevation of blood pressure requiring urgent care",
    modernMeaning: "Dhiig-kar-daran",
    example: "Hypertension crisis can damage organs.",
    category: "emergency",
    synonyms: ["hypertensive emergency"],
    isMedical: true
  },
  {
    id: 1121,
    word: "dhiig-kar-daran",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-kar-daran",
    traditionalMeaning: "hypertension crisis — cadaadis dhiig oo aad u sareeya",
    modernMeaning: null,
    example: "Dhiig-kar-daran waa xaalad degdeg ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1122,
    word: "anemia severe",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-yaraan-daran",
    traditionalMeaning: "Dhiig-yaraan-daran — critically low red blood cell levels",
    modernMeaning: "Dhiig-yaraan-daran",
    example: "Severe anemia may require blood transfusion.",
    category: "disease",
    synonyms: ["critical anemia"],
    isMedical: true
  },
  {
    id: 1123,
    word: "dhiig-yaraan-daran",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-yaraan-daran",
    traditionalMeaning: "severe anemia — dhiig aad u yaraada",
    modernMeaning: null,
    example: "Dhiig-yaraan-daran waxay sababi kartaa suuxdin.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1124,
    word: "vertigo",
    language: "english",
    type: "noun",
    somaliWord: "wareer-wareeg",
    traditionalMeaning: "Wareer-wareeg — sensation of spinning dizziness",
    modernMeaning: "Wareer-wareeg",
    example: "Vertigo makes the room feel like it is spinning.",
    category: "symptom",
    synonyms: ["spinning dizziness"],
    isMedical: true
  },
  {
    id: 1125,
    word: "wareer-wareeg",
    language: "somali",
    type: "noun",
    somaliWord: "wareer-wareeg",
    traditionalMeaning: "vertigo — wareer qofku dareemo isagoo wareegaya",
    modernMeaning: null,
    example: "Wareer-wareeg ayaa iga haya marka aan istaago.",
    category: "symptom",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1126,
    word: "colitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-mindhicir",
    traditionalMeaning: "Caabuq-mindhicir — inflammation of the colon",
    modernMeaning: "Caabuq-mindhicir",
    example: "Colitis can cause abdominal pain and diarrhea.",
    category: "disease",
    synonyms: ["colon inflammation"],
    isMedical: true
  },
  {
    id: 1127,
    word: "caabuq-mindhicir",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-mindhicir",
    traditionalMeaning: "colitis — barar ku dhaca mindhicirka weyn",
    modernMeaning: null,
    example: "Caabuq-mindhicirku wuxuu sababi karaa shuban.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1128,
    word: "tachycardia",
    language: "english",
    type: "noun",
    somaliWord: "garaac-wadne-degdeg",
    traditionalMeaning: "Garaac-wadne-degdeg — abnormally fast heart rate",
    modernMeaning: "Garaac-wadne-degdeg",
    example: "Tachycardia may cause chest discomfort.",
    category: "disease",
    synonyms: ["rapid heartbeat"],
    isMedical: true
  },
  {
    id: 1129,
    word: "garaac-wadne-degdeg",
    language: "somali",
    type: "noun",
    somaliWord: "garaac-wadne-degdeg",
    traditionalMeaning: "tachycardia — wadne si xad dhaaf ah u garaaca",
    modernMeaning: null,
    example: "Garaac-wadne-degdeg ayaa iga bilaabmay jimicsiga kadib.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1130,
    word: "bradycardia",
    language: "english",
    type: "noun",
    somaliWord: "garaac-wadne-gaabis",
    traditionalMeaning: "Garaac-wadne-gaabis — abnormally slow heart rate",
    modernMeaning: "Garaac-wadne-gaabis",
    example: "Bradycardia can lead to dizziness.",
    category: "disease",
    synonyms: ["slow heartbeat"],
    isMedical: true
  },
  {
    id: 1131,
    word: "garaac-wadne-gaabis",
    language: "somali",
    type: "noun",
    somaliWord: "garaac-wadne-gaabis",
    traditionalMeaning: "bradycardia — wadne si gaabis ah u garaaca",
    modernMeaning: null,
    example: "Garaac-wadne-gaabis wuxuu keeni karaa suuxdin.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1132,
    word: "nephritis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-kelyo",
    traditionalMeaning: "Caabuq-kelyo — inflammation of the kidneys",
    modernMeaning: "Caabuq-kelyo",
    example: "Nephritis may affect urine production.",
    category: "disease",
    synonyms: ["kidney inflammation"],
    isMedical: true
  },
  {
    id: 1133,
    word: "caabuq-kelyo",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-kelyo",
    traditionalMeaning: "nephritis — barar ku dhaca kelyaha",
    modernMeaning: null,
    example: "Caabuq-kelyo wuxuu saameeyaa sifaynta dhiigga.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1134,
    word: "hypoxia",
    language: "english",
    type: "noun",
    somaliWord: "oksijiin-yaraan",
    traditionalMeaning: "Oksijiin-yaraan — low oxygen levels in body tissues",
    modernMeaning: "Oksijiin-yaraan",
    example: "Hypoxia can damage vital organs.",
    category: "condition",
    synonyms: ["oxygen deficiency"],
    isMedical: true
  },
  {
    id: 1135,
    word: "oksijiin-yaraan",
    language: "somali",
    type: "noun",
    somaliWord: "oksijiin-yaraan",
    traditionalMeaning: "hypoxia — jirka oo oksijiin ka yaraada",
    modernMeaning: null,
    example: "Oksijiin-yaraan waxay keentaa neef-qabad.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1136,
    word: "ulcerative colitis",
    language: "english",
    type: "noun",
    somaliWord: "boog-mindhicir",
    traditionalMeaning: "Boog-mindhicir — chronic inflammatory bowel disease causing ulcers in the colon",
    modernMeaning: "Boog-mindhicir",
    example: "Ulcerative colitis causes bloody diarrhea.",
    category: "disease",
    synonyms: ["inflammatory bowel disease"],
    isMedical: true
  },
  {
    id: 1137,
    word: "boog-mindhicir",
    language: "somali",
    type: "noun",
    somaliWord: "boog-mindhicir",
    traditionalMeaning: "ulcerative colitis — boog ku samaysma mindhicirka weyn",
    modernMeaning: null,
    example: "Boog-mindhicir wuxuu sababi karaa dhiig saxarada ku jira.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1138,
    word: "sepsis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-dhiig",
    traditionalMeaning: "Caabuq-dhiig — life-threatening response to infection affecting the whole body",
    modernMeaning: "Caabuq-dhiig",
    example: "Sepsis requires immediate medical treatment.",
    category: "emergency",
    synonyms: ["blood infection"],
    isMedical: true
  },
  {
    id: 1139,
    word: "caabuq-dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-dhiig",
    traditionalMeaning: "sepsis — jirka oo si daran uga falceliya caabuq",
    modernMeaning: null,
    example: "Caabuq-dhiig waa xaalad halis ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1140,
    word: "embolism",
    language: "english",
    type: "noun",
    somaliWord: "xirid-dhiig",
    traditionalMeaning: "Xirid-dhiig — blockage of a blood vessel by a clot or foreign material",
    modernMeaning: "Xirid-dhiig",
    example: "Pulmonary embolism can cause sudden chest pain.",
    category: "condition",
    synonyms: ["vascular blockage"],
    isMedical: true
  },
  {
    id: 1141,
    word: "xirid-dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "xirid-dhiig",
    traditionalMeaning: "embolism — xidid dhiig oo xirma",
    modernMeaning: null,
    example: "Xirid-dhiig wuxuu sababi karaa neef-qabad.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1142,
    word: "osteoporosis",
    language: "english",
    type: "noun",
    somaliWord: "laf-jileec",
    traditionalMeaning: "Laf-jileec — condition causing bones to become weak and brittle",
    modernMeaning: "Laf-jileec",
    example: "Osteoporosis increases fracture risk.",
    category: "disease",
    synonyms: ["bone thinning"],
    isMedical: true
  },
  {
    id: 1143,
    word: "laf-jileec",
    language: "somali",
    type: "noun",
    somaliWord: "laf-jileec",
    traditionalMeaning: "osteoporosis — lafaha oo jilca oo daciifa",
    modernMeaning: null,
    example: "Laf-jileec waxay keeni kartaa jab fudud.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1144,
    word: "migraine",
    language: "english",
    type: "noun",
    somaliWord: "madax-xanuun-daran",
    traditionalMeaning: "Madax-xanuun-daran — severe recurring headache often with nausea",
    modernMeaning: "Madax-xanuun-daran",
    example: "Migraine attacks can last for hours.",
    category: "symptom",
    synonyms: ["severe headache"],
    isMedical: true
  },
  {
    id: 1145,
    word: "madax-xanuun-daran",
    language: "somali",
    type: "noun",
    somaliWord: "madax-xanuun-daran",
    traditionalMeaning: "migraine — madax-xanuun soo noqnoqda oo daran",
    modernMeaning: null,
    example: "Madax-xanuun-daran ayaa igu bilaabma iftiin badan.",
    category: "symptom",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1146,
    word: "cirrhosis",
    language: "english",
    type: "noun",
    somaliWord: "beer-adkaansho",
    traditionalMeaning: "Beer-adkaansho — chronic liver damage causing scarring",
    modernMeaning: "Beer-adkaansho",
    example: "Cirrhosis may result from long-term alcohol use.",
    category: "disease",
    synonyms: ["liver scarring"],
    isMedical: true
  },
  {
    id: 1147,
    word: "beer-adkaansho",
    language: "somali",
    type: "noun",
    somaliWord: "beer-adkaansho",
    traditionalMeaning: "cirrhosis — beerka oo adkaada oo nabro yeesha",
    modernMeaning: null,
    example: "Beer-adkaansho waxay saameysaa shaqada beerka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1148,
    word: "epilepsy",
    language: "english",
    type: "noun",
    somaliWord: "suuxdin-joogto",
    traditionalMeaning: "Suuxdin-joogto — neurological disorder causing recurrent seizures",
    modernMeaning: "Suuxdin-joogto",
    example: "Epilepsy requires long-term treatment.",
    category: "disease",
    synonyms: ["seizure disorder"],
    isMedical: true
  },
  {
    id: 1149,
    word: "suuxdin-joogto",
    language: "somali",
    type: "noun",
    somaliWord: "suuxdin-joogto",
    traditionalMeaning: "epilepsy — suuxdin soo noqnoqda",
    modernMeaning: null,
    example: "Suuxdin-joogto waxay u baahan tahay daawo joogto ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1150,
    word: "arthritis",
    language: "english",
    type: "noun",
    somaliWord: "barar-kala-goysyada",
    traditionalMeaning: "Barar-kala-goysyada — inflammation of joints",
    modernMeaning: "Barar-kala-goysyada",
    example: "Arthritis causes joint pain and stiffness.",
    category: "disease",
    synonyms: ["joint inflammation"],
    isMedical: true
  },
  {
    id: 1151,
    word: "barar-kala-goysyada",
    language: "somali",
    type: "noun",
    somaliWord: "barar-kala-goysyada",
    traditionalMeaning: "arthritis — kala-goysyada oo barara",
    modernMeaning: null,
    example: "Barar-kala-goysyada ayaa igu adkeeya socodka.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1152,
    word: "pneumothorax",
    language: "english",
    type: "noun",
    somaliWord: "hawo-xabadka",
    traditionalMeaning: "Hawo-xabadka — collapsed lung due to air in chest cavity",
    modernMeaning: "Hawo-xabadka",
    example: "Pneumothorax causes sudden chest pain.",
    category: "emergency",
    synonyms: ["collapsed lung"],
    isMedical: true
  },
  {
    id: 1153,
    word: "hawo-xabadka",
    language: "somali",
    type: "noun",
    somaliWord: "hawo-xabadka",
    traditionalMeaning: "pneumothorax — sambab dumo sababtoo ah hawo gudaha gasha",
    modernMeaning: null,
    example: "Hawo-xabadka waa xaalad degdeg ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1154,
    word: "dermatitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-maqaarka",
    traditionalMeaning: "Caabuq-maqaarka — inflammation of the skin",
    modernMeaning: "Caabuq-maqaarka",
    example: "Dermatitis may cause itching.",
    category: "disease",
    synonyms: ["skin inflammation"],
    isMedical: true
  },
  {
    id: 1155,
    word: "caabuq-maqaarka",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-maqaarka",
    traditionalMeaning: "dermatitis — maqaarka oo barara",
    modernMeaning: null,
    example: "Caabuq-maqaarka wuxuu keeni karaa finan.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1156,
    word: "hemorrhage",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-bax-daran",
    traditionalMeaning: "Dhiig-bax-daran — severe bleeding",
    modernMeaning: "Dhiig-bax-daran",
    example: "Hemorrhage can be life-threatening.",
    category: "emergency",
    synonyms: ["severe bleeding"],
    isMedical: true
  },
  {
    id: 1157,
    word: "dhiig-bax-daran",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-bax-daran",
    traditionalMeaning: "hemorrhage — dhiig si daran uga baxa",
    modernMeaning: null,
    example: "Dhiig-bax-daran wuxuu u baahan yahay gargaar degdeg ah.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1158,
    word: "hepatitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-beer",
    traditionalMeaning: "Caabuq-beer — inflammation of the liver",
    modernMeaning: "Caabuq-beer",
    example: "Hepatitis affects liver function.",
    category: "disease",
    synonyms: ["liver inflammation"],
    isMedical: true
  },
  {
    id: 1159,
    word: "caabuq-beer",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-beer",
    traditionalMeaning: "hepatitis — beerka oo barara",
    modernMeaning: null,
    example: "Caabuq-beer wuxuu sababi karaa cagaarshow.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1160,
    word: "fracture",
    language: "english",
    type: "noun",
    somaliWord: "jab-laf",
    traditionalMeaning: "Jab-laf — broken bone",
    modernMeaning: "Jab-laf",
    example: "The X-ray confirmed a fracture.",
    category: "injury",
    synonyms: ["broken bone"],
    isMedical: true
  },
  {
    id: 1161,
    word: "jab-laf",
    language: "somali",
    type: "noun",
    somaliWord: "jab-laf",
    traditionalMeaning: "fracture — laf jaban",
    modernMeaning: null,
    example: "Jab-laf ayaa iga dhacay gacanta.",
    category: "injury",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1162,
    word: "pancreatitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-xameetida",
    traditionalMeaning: "Caabuq-xameetida — inflammation of the pancreas",
    modernMeaning: "Caabuq-xameetida",
    example: "Pancreatitis causes severe abdominal pain.",
    category: "disease",
    synonyms: ["pancreas inflammation"],
    isMedical: true
  },
  {
    id: 1163,
    word: "caabuq-xameetida",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-xameetida",
    traditionalMeaning: "pancreatitis — xameetida oo bararta",
    modernMeaning: null,
    example: "Caabuq-xameetida wuxuu sababi karaa matag.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1164,
    word: "thrombosis",
    language: "english",
    type: "noun",
    somaliWord: "xinjiro-dhiig",
    traditionalMeaning: "Xinjiro-dhiig — formation of a blood clot inside a vessel",
    modernMeaning: "Xinjiro-dhiig",
    example: "Thrombosis may block blood flow.",
    category: "condition",
    synonyms: ["blood clot"],
    isMedical: true
  },
  {
    id: 1165,
    word: "xinjiro-dhiig",
    language: "somali",
    type: "noun",
    somaliWord: "xinjiro-dhiig",
    traditionalMeaning: "thrombosis — xinjiro ku samaysma xidid dhiig",
    modernMeaning: null,
    example: "Xinjiro-dhiig wuxuu keeni karaa xanuun lugta ah.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1166,
    word: "laryngitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-cod",
    traditionalMeaning: "Caabuq-cod — inflammation of the voice box",
    modernMeaning: "Caabuq-cod",
    example: "Laryngitis causes hoarseness.",
    category: "disease",
    synonyms: ["voice box inflammation"],
    isMedical: true
  },
  {
    id: 1167,
    word: "caabuq-cod",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-cod",
    traditionalMeaning: "laryngitis — sanduuqa codka oo barara",
    modernMeaning: null,
    example: "Caabuq-cod ayaa iga dhigay cod la'aan.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1168,
    word: "meningitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-maskax-dabool",
    traditionalMeaning: "Caabuq-maskax-dabool — inflammation of the membranes around the brain",
    modernMeaning: "Caabuq-maskax-dabool",
    example: "Meningitis can cause stiff neck and fever.",
    category: "disease",
    synonyms: ["brain membrane infection"],
    isMedical: true
  },
  {
    id: 1169,
    word: "caabuq-maskax-dabool",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-maskax-dabool",
    traditionalMeaning: "meningitis — xuubka maskaxda oo barara",
    modernMeaning: null,
    example: "Caabuq-maskax-dabool waa xanuun halis ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1170,
    word: "edema",
    language: "english",
    type: "noun",
    somaliWord: "barar-dareere",
    traditionalMeaning: "Barar-dareere — swelling caused by excess fluid in tissues",
    modernMeaning: "Barar-dareere",
    example: "Edema is common in heart failure.",
    category: "symptom",
    synonyms: ["fluid swelling"],
    isMedical: true
  },
  {
    id: 1171,
    word: "barar-dareere",
    language: "somali",
    type: "noun",
    somaliWord: "barar-dareere",
    traditionalMeaning: "edema — barar uu sababo dareere urursan",
    modernMeaning: null,
    example: "Barar-dareere ayaa lugaha iga haya.",
    category: "symptom",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1172,
    word: "appendicitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-appendix",
    traditionalMeaning: "Caabuq-appendix — inflammation of the appendix",
    modernMeaning: "Caabuq-appendix",
    example: "Appendicitis requires surgery.",
    category: "disease",
    synonyms: ["appendix inflammation"],
    isMedical: true
  },
  {
    id: 1173,
    word: "caabuq-appendix",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-appendix",
    traditionalMeaning: "appendicitis — appendix oo barara",
    modernMeaning: null,
    example: "Caabuq-appendix waa xanuun degdeg ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1174,
    word: "bronchitis",
    language: "english",
    type: "noun",
    somaliWord: "caabuq-mareenka-neef",
    traditionalMeaning: "Caabuq-mareenka-neef — inflammation of the bronchial tubes",
    modernMeaning: "Caabuq-mareenka-neef",
    example: "Bronchitis causes coughing and mucus production.",
    category: "disease",
    synonyms: ["bronchial inflammation"],
    isMedical: true
  },
  {
    id: 1175,
    word: "caabuq-mareenka-neef",
    language: "somali",
    type: "noun",
    somaliWord: "caabuq-mareenka-neef",
    traditionalMeaning: "bronchitis — marinnada hawada ee sambabada oo barara",
    modernMeaning: null,
    example: "Caabuq-mareenka-neef wuxuu keenaa qufac joogto ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1176,
    word: "anaphylaxis",
    language: "english",
    type: "noun",
    somaliWord: "xasaasiyad-daran",
    traditionalMeaning: "Xasaasiyad-daran — severe allergic reaction",
    modernMeaning: "Xasaasiyad-daran",
    example: "Anaphylaxis requires immediate injection of epinephrine.",
    category: "emergency",
    synonyms: ["severe allergy"],
    isMedical: true
  },
  {
    id: 1177,
    word: "xasaasiyad-daran",
    language: "somali",
    type: "noun",
    somaliWord: "xasaasiyad-daran",
    traditionalMeaning: "anaphylaxis — falcelin xasaasiyadeed oo halis ah",
    modernMeaning: null,
    example: "Xasaasiyad-daran waxay sababi kartaa neef-qabad.",
    category: "emergency",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1178,
    word: "glaucoma",
    language: "english",
    type: "noun",
    somaliWord: "cadaadis-indho",
    traditionalMeaning: "Cadaadis-indho — increased pressure in the eye damaging vision",
    modernMeaning: "Cadaadis-indho",
    example: "Glaucoma can lead to blindness.",
    category: "disease",
    synonyms: ["eye pressure disease"],
    isMedical: true
  },
  {
    id: 1179,
    word: "cadaadis-indho",
    language: "somali",
    type: "noun",
    somaliWord: "cadaadis-indho",
    traditionalMeaning: "glaucoma — cadaadis sare oo indhaha ku dhaca",
    modernMeaning: null,
    example: "Cadaadis-indho wuxuu saameeyaa aragga.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1180,
    word: "ulcer",
    language: "english",
    type: "noun",
    somaliWord: "boog-calooleed",
    traditionalMeaning: "Boog-calooleed — open sore inside the stomach lining",
    modernMeaning: "Boog-calooleed",
    example: "An ulcer may cause burning pain.",
    category: "disease",
    synonyms: ["stomach sore"],
    isMedical: true
  },
  {
    id: 1181,
    word: "boog-calooleed",
    language: "somali",
    type: "noun",
    somaliWord: "boog-calooleed",
    traditionalMeaning: "ulcer — boog ku samaysma caloosha",
    modernMeaning: null,
    example: "Boog-calooleed waxay keeni kartaa matag dhiig leh.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1182,
    word: "insomnia",
    language: "english",
    type: "noun",
    somaliWord: "hurdo-la'aan",
    traditionalMeaning: "Hurdo-la'aan — difficulty falling or staying asleep",
    modernMeaning: "Hurdo-la'aan",
    example: "Insomnia affects mental health.",
    category: "condition",
    synonyms: ["sleep disorder"],
    isMedical: true
  },
  {
    id: 1183,
    word: "hurdo-la'aan",
    language: "somali",
    type: "noun",
    somaliWord: "hurdo-la'aan",
    traditionalMeaning: "insomnia — hurdo la'aan ama hurdo go'go'an",
    modernMeaning: null,
    example: "Hurdo-la'aan ayaa iga dhalatay walwal.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1184,
    word: "lymphoma",
    language: "english",
    type: "noun",
    somaliWord: "kansar-qanjir",
    traditionalMeaning: "Kansar-qanjir — cancer of the lymphatic system",
    modernMeaning: "Kansar-qanjir",
    example: "Lymphoma affects white blood cells.",
    category: "disease",
    synonyms: ["lymph cancer"],
    isMedical: true
  },
  {
    id: 1185,
    word: "kansar-qanjir",
    language: "somali",
    type: "noun",
    somaliWord: "kansar-qanjir",
    traditionalMeaning: "lymphoma — kansar ku dhaca qanjirrada",
    modernMeaning: null,
    example: "Kansar-qanjir wuxuu sababi karaa qanjir barar.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },
    {
    id: 1186,
    word: "anemia",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-yaraan",
    traditionalMeaning: "Dhiig-yaraan — low red blood cell count",
    modernMeaning: "Dhiig-yaraan",
    example: "Anemia causes fatigue and weakness.",
    category: "disease",
    synonyms: ["low hemoglobin"],
    isMedical: true
  },
  {
    id: 1187,
    word: "dhiig-yaraan",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-yaraan",
    traditionalMeaning: "anemia — unugyada dhiigga oo yaraada",
    modernMeaning: null,
    example: "Dhiig-yaraan waxay keeni kartaa daal.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1188,
    word: "fibrosis",
    language: "english",
    type: "noun",
    somaliWord: "nabaro-adkaansho",
    traditionalMeaning: "Nabaro-adkaansho — thickening and scarring of tissue",
    modernMeaning: "Nabaro-adkaansho",
    example: "Fibrosis reduces organ function.",
    category: "disease",
    synonyms: ["tissue scarring"],
    isMedical: true
  },
  {
    id: 1189,
    word: "nabaro-adkaansho",
    language: "somali",
    type: "noun",
    somaliWord: "nabaro-adkaansho",
    traditionalMeaning: "fibrosis — unugyo adkaada sababo nabro darteed",
    modernMeaning: null,
    example: "Nabaro-adkaansho waxay saameysaa sambabada.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1190,
    word: "seizure",
    language: "english",
    type: "noun",
    somaliWord: "suuxdin",
    traditionalMeaning: "Suuxdin — sudden uncontrolled electrical activity in the brain",
    modernMeaning: "Suuxdin",
    example: "A seizure may cause shaking.",
    category: "symptom",
    synonyms: ["convulsion"],
    isMedical: true
  },
  {
    id: 1191,
    word: "suuxdin",
    language: "somali",
    type: "noun",
    somaliWord: "suuxdin",
    traditionalMeaning: "seizure — dhaqdhaqaaq maskaxeed oo lama filaan ah",
    modernMeaning: null,
    example: "Suuxdin ayaa ku dhacday bukaanka.",
    category: "symptom",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1192,
    word: "cataract",
    language: "english",
    type: "noun",
    somaliWord: "indho-madow",
    traditionalMeaning: "Indho-madow — clouding of the eye lens",
    modernMeaning: "Indho-madow",
    example: "Cataract surgery restores vision.",
    category: "disease",
    synonyms: ["lens opacity"],
    isMedical: true
  },
  {
    id: 1193,
    word: "indho-madow",
    language: "somali",
    type: "noun",
    somaliWord: "indho-madow",
    traditionalMeaning: "cataract — muraayadda indhaha oo madoobaata",
    modernMeaning: null,
    example: "Indho-madow wuxuu yareeyaa aragga.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1194,
    word: "hemophilia",
    language: "english",
    type: "noun",
    somaliWord: "dhiig-joogsi-la'aan",
    traditionalMeaning: "Dhiig-joogsi-la'aan — genetic disorder affecting blood clotting",
    modernMeaning: "Dhiig-joogsi-la'aan",
    example: "Hemophilia causes prolonged bleeding.",
    category: "disease",
    synonyms: ["bleeding disorder"],
    isMedical: true
  },
  {
    id: 1195,
    word: "dhiig-joogsi-la'aan",
    language: "somali",
    type: "noun",
    somaliWord: "dhiig-joogsi-la'aan",
    traditionalMeaning: "hemophilia — dhiig aan si fudud u istaagin",
    modernMeaning: null,
    example: "Dhiig-joogsi-la'aan waa cudur hidde-side ah.",
    category: "disease",
    synonyms: [],
    isMedical: true
  },

  {
    id: 1196,
    word: "malnutrition",
    language: "english",
    type: "noun",
    somaliWord: "nafaqo-darro",
    traditionalMeaning: "Nafaqo-darro — lack of proper nutrition",
    modernMeaning: "Nafaqo-darro",
    example: "Malnutrition weakens the immune system.",
    category: "condition",
    synonyms: ["undernutrition"],
    isMedical: true
  },
  {
    id: 1197,
    word: "nafaqo-darro",
    language: "somali",
    type: "noun",
    somaliWord: "nafaqo-darro",
    traditionalMeaning: "malnutrition — jirka oo nafaqo ka yaraada",
    modernMeaning: null,
    example: "Nafaqo-darro waxay saameysaa carruurta.",
    category: "condition",
    synonyms: [],
    isMedical: true
  },
];

// Categories for filtering
const medicalCategories = [
  { key: 'all',         label: 'All' },
  { key: 'anatomy',     label: 'Anatomy' },
  { key: 'disease',     label: 'Diseases' },
  { key: 'symptom',     label: 'Symptoms' },
  { key: 'treatment',   label: 'Treatment' },
  { key: 'profession',  label: 'Profession' },
  { key: 'prevention',  label: 'Prevention' },
  { key: 'nutrition',   label: 'Nutrition' },
  { key: 'facility',    label: 'Facilities' },
];